autowarefoundation/autoware_core

.gitignore, .pre-commit-config.yaml, mkdocs.yaml
Copied and modified from https://github.com/autowarefoundation/autoware.universe.
=> chore: add config files

.github/sync-files.yaml, .github/workflows/sync-files.yaml
Sync files that will be added in https://github.com/autowarefoundation/autoware/pull/56.
=> chore: sync issue and PR templates

.pre-commit-config.yaml, README.md
Signed-off-by: Shumpei Wakabayashi <shumpei.wakabayashi@tier4.jp>
Update README with more concrete information.
Related PR: https://github.com/autowarefoundation/autoware.universe/pull/970#issuecomment-1139188704
The README explanation is based on https://github.com/autowarefoundation/autoware which says
> Main repository for high-quality, stable ROS packages for Autonomous Driving.
> Based on [Autoware.Auto](https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto) and [Autoware.Universe](https://github.com/autowarefoundation/autoware.universe).
I mainly changed the 2nd line because IMO 
- relationship of AutowareAuto is ambiguous
- relationship of universe should be described.
The universe explanation is based on https://github.com/autowarefoundation/autoware.
The PR author …
=> docs: update README

.github/actions/build-and-test-differential/action.yaml, .github/workflows/build-and-test-differential.yaml
This updates the build-and-test-differential workflow using the one from Autoware.Universe.
Following updates are made:
- split common steps used among build-and-test and build-and-test-differential-self-hosted into action file
- show disk space before/after the workflow
- add label protection
- https://github.com/autowarefoundation/autoware.core/issues/92
https://github.com/autowarefoundation/autoware.core/actions/runs/11697227597?pr=89
The PR author **must** check the checkboxes below when creating the PR.
The PR reviewers **must** check the checkboxes below before approval.
The PR author **must** check the checkboxes below before merging.
After all checkboxes are checked, anyone who has write access can merge the PR.
[contribution guidelines]: …
=> ci: update build-and-test-differential workflow

.cppcheck_suppressions, .github/workflows/cppcheck-differential.yaml
This PR added the minimal `.cppcheck_suppressions` to pass the `cppcheck-differential`.
- https://github.com/autowarefoundation/autoware.core/pull/106
- https://github.com/autowarefoundation/autoware.core/pull/100#issuecomment-2518972150
None.
None.
None.
=> fix(autoware_geography_utils): fix `cppcheck-differential` errors

build_depends.repos
This PR minimizes the dependent repositories in `build_depends.repos`.
Once `autoware_msgs` v1.3.0 will be released, we can also remove `autoware_msgs` dependency. https://github.com/ros/rosdistro/pull/43812
None.
None.
None.
=> refactor(build_depends): minimize dependent repositories

.github/CODEOWNERS-manual, .github/sync-files.yaml
This PR adds @autowarefoundation/autoware-core-global-codeowners  team to all packages.
And removes the manual code owners.
Detailed explanation of how the ordering in this file works: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#example-of-a-codeowners-file
https://github.com/autowarefoundation/autoware.core/blob/701e814822e67d119345a9e41ee702ecd06f772e/.github/CODEOWNERS
```
common/autoware_geography_utils/** anh.nguyen.2@tier4.jp masahiro.sakamoto@tier4.jp ryu.yamamoto@tier4.jp shintaro.sakoda@tier4.jp taiki.yamada@tier4.jp yamato.ando@tier4.jp
* mfc@autoware.org ryohsuke.mitsudome@tier4.jp yutaka.kondo@tier4.jp
```
Any rule that comes later overrides the rules above.
This means, because the later …
=> ci(sync-files): add global code owners

.github/sync-files.yaml
Because it was adding it with single quotes, pre-commit replaces it with double quotes. And this way it creates a useless PR.
sync-files commit
pre-commit auto-fix commit
end result:
- https://github.com/autowarefoundation/autoware.core/pull/116
Follow up from:
- https://github.com/autowarefoundation/autoware.core/pull/114
- https://github.com/autowarefoundation/autoware.core/actions/runs/12257350792
- https://github.com/autowarefoundation/autoware.core/pull/116
The pr was self-closed by the sync-files action ✅
None.
None.
None.
=> ci(sync-files): escape double quotes to avoid pre-commit modifying the file

common/autoware_node/CMakeLists.txt
This pull request fixes the following build error.
```bash
+ colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-select autoware_test_node
Starting >>> autoware_test_node
--- stderr: autoware_test_node                              
/usr/bin/ld: /home/shintarosakoda/autoware/install/autoware_node/lib/libautoware_node.a(node.cpp.o): warning: relocation against `g_rcutils_logging_initialized' in read-only section `.text'
/usr/bin/ld: /home/shintarosakoda/autoware/install/autoware_node/lib/libautoware_node.a(node.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTVN8autoware4node4NodeE' can not be used when making a shared object。 -fPIC を付けて再コンパイルしてください。
/usr/bin/ld: 最終リンクに失敗しました: bad value
collect2: error: ld returned 1 exit status
gmake[2]: *** …
```
=> fix: change autoware_node from a static library to a shared library

.cppcheck_suppressions
This PR adds "unmatchedSuppression" to the suppression list for cppcheck. 
When we run cppcheck-differential against a PR, it will only run against the packages that were modified. If the modified packages do not contain any errors that is listed in .cppcheck_suppressions, it will complain that we have unnecessary suppression given to cppcheck.
For example, [this PR](https://github.com/autowarefoundation/autoware.core/pull/124) fails with cppcheck because the modified package does not contain error from  `missingIncludeSystem`.  (report is [here](https://github.com/autowarefoundation/autoware.core/actions/runs/12353534061/job/34472850728?pr=124))
- https://github.com/autowarefoundation/autoware.core/pull/124
None.
None.
None.
=> ci: add unmatchedSuppression to cppcheck suppressions

common/autoware_geography_utils/test/test_lanelet2_projector.cpp
This adds `lanelet2_projector` test.
- Link
None.
None.
None.
=> test(autoware_geography_utils): add `lanelet2_projector` test

common/autoware_geography_utils/include/autoware/geography_utils/height.hpp, common/autoware_geography_utils/include/autoware/geography_utils/projection.hpp, common/autoware_geography_utils/src/height.cpp, common/autoware_geography_utils/src/lanelet2_projector.cpp, common/autoware_geography_utils/src/projection.cpp
This PR applies modern C++17 style to `autoware_geography_utils`.
- Link
None.
None.
None.
=> refactor(autoware_geography_utils): apply modern C++17 style

.github/CODEOWNERS-manual
This PR adds @autowarefoundation/autoware-core-global-codeowners to `.github` CODEOWNERS.
None.
None.
None.
=> chore(.github): add `.github` CODEOWNERS

.cppcheck_suppressions
Some packages have functions that are only used in `autoware.universe`. They cause problems in the CI check. https://github.com/autowarefoundation/autoware.core/pull/150#issuecomment-2572425103
This pull request adds "unusedFunction" to .cppcheck_supressions, following veqcc-san's recommendation. https://github.com/autowarefoundation/autoware.core/pull/150#issuecomment-2574450600
- [Link](https://github.com/autowarefoundation/autoware.core/pull/150)
None.
None.
None.
None.
=> ci: add "unusedFunction" to .cppcheck_supressions

.cppcheck_suppressions
This PR resolves https://github.com/autowarefoundation/autoware.core/pull/141#issuecomment-2574840383 issue.
- Link
None.
None.
None.
=> chore(.cppcheck_suppressions): append `missingInclude`

common/autoware_osqp_interface/CMakeLists.txt, common/autoware_osqp_interface/design/osqp_interface-design.md, common/autoware_osqp_interface/include/autoware/osqp_interface/csc_matrix_conv.hpp, common/autoware_osqp_interface/include/autoware/osqp_interface/osqp_interface.hpp, common/autoware_osqp_interface/include/autoware/osqp_interface/visibility_control.hpp, common/autoware_osqp_interface/package.xml, common/autoware_osqp_interface/src/csc_matrix_conv.cpp, common/autoware_osqp_interface/src/osqp_interface.cpp, common/autoware_osqp_interface/test/test_csc_matrix_conv.cpp, common/autoware_osqp_interface/test/test_osqp_interface.cpp
**Parent Issue:**   [#164](https://github.com/autowarefoundation/autoware.core/issues/164) 
Should be handled together with [#9890](https://github.com/autowarefoundation/autoware.universe/pull/9890)
None.
None.
None.
=> feat(autoware_osqp_interface): porting autoware_osqp_interface package from autoware.universe

.github/workflows/build-and-test-differential.yaml
This PR modifies the build-and-test-differential action to use require-label action instead of make-sure-label-is-present. 
The new action will report failure if the label is not present so that we can use it as required status for other PRs.
This is similar to what we were trying to solve in Autoware.Universe with this PR: https://github.com/autowarefoundation/autoware.universe/pull/9709
- Link
None.
None.
None.
=> ci: use require-label action to check labels

common/autoware_geography_utils/CHANGELOG.rst, common/autoware_geography_utils/package.xml, common/autoware_kalman_filter/CHANGELOG.rst, common/autoware_kalman_filter/package.xml, common/autoware_node/CHANGELOG.rst, common/autoware_node/package.xml, common/autoware_osqp_interface/CHANGELOG.rst, common/autoware_osqp_interface/package.xml, common/autoware_point_types/CHANGELOG.rst, common/autoware_point_types/package.xml, common/autoware_qp_interface/CHANGELOG.rst, common/autoware_qp_interface/package.xml, demos/autoware_test_node/CHANGELOG.rst, demos/autoware_test_node/package.xml, localization/autoware_localization_util/CHANGELOG.rst, localization/autoware_localization_util/package.xml
bump version to 0.2.0
https://github.com/tier4/autoware.core/commits/v0.41.0/
None.
None.
None.
=> chore: bump version to 0.2.0

common/autoware_point_types/include/autoware/point_types/memory.hpp
These layout checks were present in the pointcloud preprocessor.
However, linking against it it slow and several packages that would need these checks do not really depend on the pointcloud preprocessor, so I think it is better to have the checks next to the definitions of the point types.
- Link
Temporarily used this checks on nodes like centerpoint and worked as expected
None.
None.
None.
=> feat(point_types): reimplemented the pointcloud preprocesor's memory layout checks

.github/sync-files.yaml, .github/workflows/update-codeowners-from-packages.yaml
When this workflow tenerates a PR, we need to add the label manually to make it pass the CI.
This PR automates that.
I will test with manual dispatch on the sync-files change to see if `sd` command works as expected.
- ✅ https://github.com/autowarefoundation/autoware.core/pull/212#issuecomment-2674326969
None.
None.
None.
=> ci(update-codeowners-from-packages): add build label

common/autoware_geography_utils/src/lanelet2_projector.cpp, common/autoware_geography_utils/test/test_lanelet2_projector.cpp, common/autoware_geography_utils/test/test_projection.cpp
Add LocalCaretsian (WGS84) projection support to map_loader.
- https://github.com/autowarefoundation/autoware.universe/pull/9238
- https://github.com/autowarefoundation/autoware_msgs/pull/118
None.
None.
None.
=> feat(autoware_geography_utils): add support for local cartesian projection

testing/autoware_planning_test_manager/CMakeLists.txt, testing/autoware_planning_test_manager/README.md, testing/autoware_planning_test_manager/include/autoware/planning_test_manager/autoware_planning_test_manager.hpp, testing/autoware_planning_test_manager/include/autoware/planning_test_manager/autoware_planning_test_manager_utils.hpp, testing/autoware_planning_test_manager/include/autoware_planning_test_manager/autoware_planning_test_manager.hpp, testing/autoware_planning_test_manager/include/autoware_planning_test_manager/autoware_planning_test_manager_utils.hpp, testing/autoware_planning_test_manager/package.xml, testing/autoware_planning_test_manager/src/autoware_planning_test_manager.cpp
We are porting autoware_planning_test_manager to autoware.core, and this PR adds the package to core.
Following modification were added:
- reset version in package.xml and remove CHANGELOG.rst
- modify include file directory structure to match with [Autoware Coding Guideline](https://autowarefoundation.github.io/autoware-documentation/main/contributing/coding-guidelines/ros-nodes/directory-structure/#directory-structure)
- https://github.com/autowarefoundation/autoware.core/issues/198
The whole project is built correctly locally. 
The github CICD errors are related to dependence to autoware.universe.
The launch failed locally and will be re-executed after the dependency resolved.
**Update:** Planning simulator works well in the following code version: …
=> feat(autoware_planning_test_manager): porting autoware_planning_test_manager package from autoware.universe

.cspell.json, planning/autoware_path_generator/include/autoware/path_generator/utils.hpp, planning/autoware_path_generator/package.xml, planning/autoware_path_generator/src/node.cpp, planning/autoware_path_generator/src/utils.cpp
based on
https://github.com/mitukou1109/autoware.core/pull/2, fix for latest main branch ( thanks @mitukou1109 
This PR adds a feature to cut the path before the self-intersection to avoid incorrect neighbor search.
1 ) not cut if no self intersection
2 ) 
cut if self intersection
not cut after passing self intersection point
- https://tier4.atlassian.net/browse/RT1-9047 (tier4 internal)
- Link
Psim
[Screencast from 2025年02月07日 15時33分28秒.webm](https://github.com/user-attachments/assets/45dfbbc7-6d82-4589-be6e-a11bfa3739c0)
None.
None.
None.
=> feat(path_generator): add path cut feature

testing/autoware_test_utils/README.md
fix invalid link
after fixing
- https://autowarefoundation.github.io/autoware.core/main/testing/autoware_planning_test_manager/
- https://github.com/autowarefoundation/autoware.core/blob/main/testing/autoware_planning_test_manager/src/autoware_planning_test_manager.cpp
- Link
click links
None.
None.
None.
=> docs(autoware_test_utils): fix invalid link

common/autoware_interpolation/package.xml
In package autoware_interpolation some packages are used, not mentioned in package.xml. This PR adds them.
geometry_msgs:
https://github.com/autowarefoundation/autoware.core/blob/fbbccdb4eeb07128285a590d98e378fa85ca0bb6/common/autoware_interpolation/include/autoware/interpolation/spherical_linear_interpolation.hpp#L20
tf2:
https://github.com/autowarefoundation/autoware.core/blob/fbbccdb4eeb07128285a590d98e378fa85ca0bb6/common/autoware_interpolation/include/autoware/interpolation/spherical_linear_interpolation.hpp#L22
tf2_geometry_msgs:
https://github.com/autowarefoundation/autoware.core/blob/fbbccdb4eeb07128285a590d98e378fa85ca0bb6/common/autoware_interpolation/include/autoware/interpolation/spherical_linear_interpolation.hpp#L27
None.
=> fix(autoware_interpolation): add missing dependencies

common/autoware_trajectory/src/pose.cpp
Fix a bug of align_orientation_with_trajectory_direction.
Previously, we have used the following geometric relations to align the orientation.
However, if the rotation angle is 0 or M_PI, the rotation axis is not unique.
In this PR, I specify rotation axis as z-axis when rotation axis is 0 or M_PI.
- Link
~~One of the reviewer @sasakisasaki is doing the tests now.~~ → **Now tested as follows**.
The PR author @yhisaki and @sasakisasaki are having the discussion in the same office.
**(Written by @sasakisasaki at 16:00 JST 4th Mar. 2025)** I checked as the following steps.
- Before applying the fix provided by this PR, I ran the scenario simulator tests on my local environment.
- I tried the case when the rotation angle is exactly zero and verified the normalized rotation …
=> fix(autoware_trajectory): fix a bug of align_orientation_with_trajectory_direction

common/autoware_object_recognition_utils/CMakeLists.txt, common/autoware_object_recognition_utils/README.md, common/autoware_object_recognition_utils/include/autoware/object_recognition_utils/conversion.hpp, common/autoware_object_recognition_utils/include/autoware/object_recognition_utils/geometry.hpp, common/autoware_object_recognition_utils/include/autoware/object_recognition_utils/matching.hpp, common/autoware_object_recognition_utils/include/autoware/object_recognition_utils/object_classification.hpp, common/autoware_object_recognition_utils/include/autoware/object_recognition_utils/object_recognition_utils.hpp, common/autoware_object_recognition_utils/include/autoware/object_recognition_utils/predicted_path_utils.hpp, common/autoware_object_recognition_utils/include/autoware/object_recognition_utils/transform.hpp, common/autoware_object_recognition_utils/package.xml, common/autoware_object_recognition_utils/src/conversion.cpp, common/autoware_object_recognition_utils/src/predicted_path_utils.cpp, common/autoware_object_recognition_utils/test/src/test_conversion.cpp, common/autoware_object_recognition_utils/test/src/test_geometry.cpp, common/autoware_object_recognition_utils/test/src/test_matching.cpp, common/autoware_object_recognition_utils/test/src/test_object_classification.cpp, common/autoware_object_recognition_utils/test/src/test_predicted_path_utils.cpp
porting autoware_object_recognition_utils to core repo
- Link https://github.com/autowarefoundation/autoware.core/issues/226
1. colcon build with all autoware packages
2. finish A-2-B task in planning simulator, with dummy cars and pedestrians
- Should be **merged together** with universe repo pr https://github.com/autowarefoundation/autoware.universe/pull/10215
None.
None.
=> feat(autoware_object_recognition_utils): move to core

testing/autoware_test_utils/include/autoware_test_utils/autoware_test_utils.hpp
Set stamp so that we can test latency abnormality.
- https://github.com/autowarefoundation/autoware.universe/pull/10241
PASS CI/CD
None.
None.
None.
=> fix(autoware_test_utils): set timestamp in building trajectory msg

planning/autoware_planning_factor_interface/CMakeLists.txt, planning/autoware_planning_factor_interface/README.md, planning/autoware_planning_factor_interface/include/autoware/planning_factor_interface/planning_factor_interface.hpp, planning/autoware_planning_factor_interface/package.xml, planning/autoware_planning_factor_interface/src/planing_factor_interface.cpp
porting autoware_planning_factor_interface to core repo
- Link https://github.com/autowarefoundation/autoware.core/issues/226
1. colcon build with all autoware packages
2. finish A-2-B task in planning simulator, with dummy cars and pedestrians
3. ci of core repo
Should be merged together with universe repo pr https://github.com/autowarefoundation/autoware.universe/pull/10243
None.
None.
=> feat(autoware_planning_factor_interface): move to core

planning/autoware_path_generator/test/test_path_generator_node_interface.cpp
This PR fixes the node interface test. The ego's current pose was set to the origin, which meant that it was not on the route.
internal: https://star4.slack.com/archives/C0575HP7NJG/p1741562457780569
```
colcon test --packages-select autoware_path_generator --event-handlers console_cohesion+
```
Result (the value display is for debugging and is not part of the PR):
```
1: [ RUN      ] PlanningModuleInterfaceTest.NodeTestWithExceptionTrajectory
1: [INFO] [1741576257.180988020] [path_generator]: length: 12.914741, start: 4.440289, end: 8.474452
1: [INFO] [1741576257.281931107] [path_generator]: length: 12.914741, start: 4.440289, end: 8.474452
1: [INFO] [1741576257.382559835] [path_generator]: length: 12.914741, start: 4.440289, end: 8.474452
1: [INFO] [1741576257.483280238] …
```
=> fix(path_generator): set current pose appropriately in test

planning/autoware_path_generator/src/node.cpp, planning/autoware_path_generator/src/node.hpp
This PR adds a feature to publish hazard signals to `path_generator`. Currently it always sends `HazardLightsCommand::NO_COMMAND`.
Psim (The warning `The operation mode is changed, but the HazardLightsCommand is not received yet` is no longer showing up)
[Screencast from 2025年03月10日 14時18分37秒.webm](https://github.com/user-attachments/assets/8d6df6a6-568e-453d-b986-272628cd53f0)
None.
None.
None.
=> feat(path_generator): publish hazard signal

codecov.yaml
https://github.com/autowarefoundation/autoware.core/issues/156
related discussion https://github.com/orgs/autowarefoundation/discussions/5861
None.
None.
None.
=> fix: eliminate nonessential directories in test coverage statistics

common/autoware_trajectory/include/autoware/trajectory/detail/interpolated_array.hpp, common/autoware_trajectory/include/autoware/trajectory/interpolator/akima_spline.hpp, common/autoware_trajectory/include/autoware/trajectory/interpolator/cubic_spline.hpp, common/autoware_trajectory/include/autoware/trajectory/interpolator/detail/interpolator_common_interface.hpp, common/autoware_trajectory/include/autoware/trajectory/interpolator/detail/interpolator_mixin.hpp, common/autoware_trajectory/include/autoware/trajectory/interpolator/detail/nearest_neighbor_common_impl.hpp, common/autoware_trajectory/include/autoware/trajectory/interpolator/detail/stairstep_common_impl.hpp, common/autoware_trajectory/include/autoware/trajectory/interpolator/interpolator.hpp, common/autoware_trajectory/include/autoware/trajectory/interpolator/linear.hpp, common/autoware_trajectory/include/autoware/trajectory/interpolator/nearest_neighbor.hpp, common/autoware_trajectory/include/autoware/trajectory/interpolator/spherical_linear.hpp, common/autoware_trajectory/include/autoware/trajectory/interpolator/stairstep.hpp, common/autoware_trajectory/include/autoware/trajectory/path_point.hpp, common/autoware_trajectory/include/autoware/trajectory/path_point_with_lane_id.hpp, common/autoware_trajectory/include/autoware/trajectory/point.hpp, common/autoware_trajectory/include/autoware/trajectory/pose.hpp, common/autoware_trajectory/include/autoware/trajectory/trajectory_point.hpp, common/autoware_trajectory/src/interpolator/akima_spline.cpp, common/autoware_trajectory/src/interpolator/cubic_spline.cpp, common/autoware_trajectory/src/interpolator/linear.cpp, common/autoware_trajectory/src/interpolator/spherical_linear.cpp, common/autoware_trajectory/src/path_point.cpp, common/autoware_trajectory/src/path_point_with_lane_id.cpp, common/autoware_trajectory/src/point.cpp, common/autoware_trajectory/src/pose.cpp, common/autoware_trajectory/src/trajectory_point.cpp
- I removed `nodiscard` for const member functions because they have no side effect
- I removed reference to scalar type arguments because it is a bit overhead
- I modifed `build` function to accept universal reference
- Link
Unit test passes
None.
None.
None.
=> refactor(autoware_trajectory): use nodiscard for mutables, fix reference to scalar type

.github/CODEOWNERS-manual
@autowarefoundation/autoware-core-global-codeowners setting is working for modifications to existing packages thanks to https://github.com/autowarefoundation/autoware.core/pull/114 , but for new package creations like in https://github.com/autowarefoundation/autoware.core/pull/231, the code owner setting is still left empty.
This PR modifies the settings so that if a PR does not have a code owner assigned, it will be set to @autowarefoundation/autoware-core-global-codeowners.
- https://github.com/autowarefoundation/autoware.core/pull/104
- https://github.com/autowarefoundation/autoware.core/pull/114
None.
None.
None.
=> chore(CODEOWNER-manual): set `autoware-core-global-codeowners` if there is no code owner

planning/autoware_path_generator/include/autoware/path_generator/utils.hpp, planning/autoware_path_generator/src/node.cpp, planning/autoware_path_generator/src/utils.cpp
This PR fixes path bound generation of `path_generator` to extend the path bound to out of route to ensure a sufficient drivable area at the start and goal.
Additionally, each point on the path bound will have the correct z coordinate value for visualization.
internal: https://star4.slack.com/archives/C0575HP7NJG/p1741754878096839?thread_ts=1741739730.348109&cid=C0575HP7NJG
Psim
Before:
After:
None.
None.
None.
=> fix(path_generator): fix path bound generation

common/autoware_lanelet2_utils/include/autoware/lanelet2_utils/intersection.hpp, common/autoware_lanelet2_utils/include/autoware/lanelet2_utils/kind.hpp, common/autoware_lanelet2_utils/include/autoware/lanelet2_utils/topology.hpp, common/autoware_lanelet2_utils/src/intersection.cpp, common/autoware_lanelet2_utils/src/kind.cpp, common/autoware_lanelet2_utils/src/topology.cpp, common/autoware_lanelet2_utils/test/intersection.cpp, common/autoware_lanelet2_utils/test/kind.cpp, common/autoware_lanelet2_utils/test/topology.cpp
Signed-off-by: Mamoru Sobue <mamoru.sobue@tier4.jp>
update the `include/` structure to align with awf policy.
https://github.com/autowarefoundation/autoware.core/pull/244
- Link
unit test passes, and there are no other packages using this package
None.
None.
None.
=> chore(lanelet2_utils): change header directory structure

.github/CODEOWNERS-manual
Reverts autowarefoundation/autoware.core#247
The above PR was meant to add autoware-core-global-codeowners as a default code reviewer if there are no code-owners, but it actually overrides the code reviewer for all the PR.
We are reverting it until we find a good solution.
=> chore(CODEOWNERS-manual): set global code owners for files starting with "."

common/autoware_osqp_interface/design/osqp_interface-design.md, common/autoware_osqp_interface/include/autoware/osqp_interface/csc_matrix_conv.hpp, common/autoware_osqp_interface/include/autoware/osqp_interface/osqp_interface.hpp, common/autoware_osqp_interface/src/osqp_interface.cpp, common/autoware_osqp_interface/test/test_osqp_interface.cpp
Core changes for https://github.com/autowarefoundation/autoware.universe/pull/10276
- Link
None.
None.
None.
=> feat(osqp_interface): core changes for additional failure logging

.github/sync-files.yaml, NOTICE, README.md, common/autoware_geography_utils/CHANGELOG.rst, common/autoware_kalman_filter/CHANGELOG.rst, common/autoware_node/CHANGELOG.rst, common/autoware_node/README.md, common/autoware_node/package.xml, common/autoware_osqp_interface/CHANGELOG.rst, common/autoware_point_types/CHANGELOG.rst, common/autoware_qp_interface/CHANGELOG.rst, demos/autoware_test_node/CHANGELOG.rst, localization/autoware_localization_util/CHANGELOG.rst, mkdocs.yaml, planning/autoware_path_generator/src/utils.cpp, planning/autoware_planning_factor_interface/README.md, testing/autoware_test_utils/README.md
Since https://github.com/orgs/autowarefoundation/discussions/5684 is closed, this PR renames `autoware_core`.
- https://github.com/autowarefoundation/autoware/pull/5902
None.
None.
None.
=> chore: rename from `autoware.core` to `autoware_core`

planning/autoware_planning_factor_interface/include/autoware/planning_factor_interface/planning_factor_interface.hpp, planning/autoware_planning_factor_interface/src/planing_factor_interface.cpp
I fixed the functions so that we can set shif length and velocity for each control points.
```patch
diff --git a/planning/autoware_planning_factor_interface/include/autoware/planning_factor_interface/planning_factor_interface.hpp b/planning/autoware_planning_factor_interface/include/autoware/planning_factor_interface/planning_factor_interface.hpp
index a88fdbb..63d72a3 100644
--- a/planning/autoware_planning_factor_interface/include/autoware/planning_factor_interface/planning_factor_interface.hpp
+++ b/planning/autoware_planning_factor_interface/include/autoware/planning_factor_interface/planning_factor_interface.hpp
/**
@@ -151,26 +155,29 @@ public:
* @param behavior of this planning factor.
* @param safety factor.
* @param driving direction.
-   * @param target velocity of the control …
```
=> fix(planning_factor_interface): set control point data independently

sensing/autoware_crop_box_filter/CMakeLists.txt, sensing/autoware_crop_box_filter/README.md, sensing/autoware_crop_box_filter/config/crop_box_filter_node.param.yaml, sensing/autoware_crop_box_filter/include/autoware/crop_box_filter/crop_box_filter_node.hpp, sensing/autoware_crop_box_filter/launch/crop_box_filter_node.launch.xml, sensing/autoware_crop_box_filter/package.xml, sensing/autoware_crop_box_filter/src/crop_box_filter_node.cpp, sensing/autoware_crop_box_filter/test/test_crop_box_filter_node.cpp
Extracted from universe-sensing-pointcloud-preprocessor and reimplemented on core repo
**Reimplementation content**
1. remove dependency to packages under universe repo
2. refactering package.xml and CMakeList.txt
3. add readme
4. add unit test code checking “only expected point pass the filter”
4.1 construct a input pointcloud which contain points both inside and outside the box, and pass it to the filter
4.2 check the total number of points in the output pointcloud, whether it equals expectation
4.3 check every point of the output pointcloud, whether it should pass the filter
**What's the difference from original code**
1. set polygon pulisher's frenquency from always to when someone subscribed
2. add a launch paramter "input_pointcloud_frame", thus we can get pointcloud transformation …
=> feat(autoware_crop_box_filter): reimplementation in core repo

.github/sync-files.yaml, codecov.yaml
This PR removes the connection of `codecov.yaml` from the sync-file-templates. The file is specialized enough for this purpose.
- https://github.com/autowarefoundation/autoware_core/pull/259#issuecomment-2750270785
- https://github.com/autowarefoundation/autoware_core/pull/257
Ran they workflow manually.
https://github.com/autowarefoundation/autoware_core/actions/runs/14054177269
It closed the relevant PR ✅
- https://github.com/autowarefoundation/autoware_core/pull/259#event-16969129899
None.
None.
None.
=> ci(sync-files.yaml): remove codecov.yaml from the list

planning/autoware_path_generator/src/utils.cpp
The compiler on Ubuntu Noble warns about a redundant move, and `-Werror` causes the build to fail. This PR removes that move.
```
/workspaces/ros2/src/autoware/core/autoware.core/planning/autoware_path_generator/src/utils.cpp: In function ‘std::optional<std::vector<lanelet::ConstLanelet> > autoware::path_generator::utils::get_lanelets_within_route(const lanelet::ConstLanelet&, const autoware::path_generator::PlannerData&, const geometry_msgs::msg::Pose&, double, double)’:
/workspaces/ros2/src/autoware/core/autoware.core/planning/autoware_path_generator/src/utils.cpp:96:64: error: redundant move in initialization [-Werror=redundant-move]
96 |   lanelet::ConstLanelets lanelets(std::move(*backward_lanelets));
|                                                                ^ …
```
=> fix(autoware_path_generator): remove redundant move

common/autoware_vehicle_info_utils/src/vehicle_info.cpp, common/autoware_vehicle_info_utils/test/test_vehicle_info_utils.cpp
https://github.com/autowarefoundation/autoware.core/issues/131
None.
None.
None.
=> test(autoware_vehicle_info_utils): add tests for missed lines

common/autoware_vehicle_info_utils/CMakeLists.txt
The test uses `ament_index_cpp`, but it doesn't link against it. The test is created with a non-ament_cmake_auto macro, so there's no opportunity to auto link against the test dependencies. I'm not sure how this works currently.
- Link
Ubuntu Noble ROS Rolling with https://github.com/ament/ament_cmake/pull/571
None.
None.
None.
=> fix(autoware_vehicle_info_utils): test not linking to ament_index_cpp

planning/autoware_path_generator/test/test_turn_signal.cpp
related to : https://github.com/autowarefoundation/autoware_core/pull/253#discussion_r2014003092
Confirm that the position of the get is approximately where the end angle appears to be 15deg different from the end angle. Add a test with this value as true.
```
x: 3760.89359759847 y: 73749.3592002149
```
- Link
unit test 
```
autoware_path_generator/test_results/autoware_path_generator/test_autoware_path_generator.gtest.xml
- b
test 1
Start 1: test_autoware_path_generator
1: Test command: /usr/bin/python3 "-u" "/opt/ros/humble/share/ament_cmake_ros/cmake/run_test_isolated.py" "/home/kosuke55/pilot-auto/build/autoware_path_generator/test_results/autoware_path_generator/test_autoware_path_generator.gtest.xml" "--package-name" "autoware_path_generator" "--output-file" …
```
=> test(autoware_path_generator): add turn signal RequiredEndPoint position test

.github/actions/build-and-test-differential/action.yaml, .github/sync-files.yaml, .github/workflows/build-and-test-daily.yaml, .github/workflows/build-and-test-differential-self-hosted.yaml, .github/workflows/build-and-test-differential.yaml, .github/workflows/build-and-test.yaml, .github/workflows/check-build-depends.yaml, build_depends.repos
Reverts autowarefoundation/autoware_core#239
Since it takes over an hour to build the `autoware:core-common-devel` image with the new `autoware_internal_msgs`, I will temporarily revert this PR.
Ref.
- https://github.com/autowarefoundation/autoware/pull/5947
Test
- https://github.com/autowarefoundation/autoware/actions/runs/14104971773
=> revert: "feat: no longer use `build_depends.repos`"

control/autoware_simple_pure_pursuit/src/simple_pure_pursuit.cpp
This modifies the default QoS settings for control command output from autoware_simple_pure_pursuit to transient local. This is because AWSIM subsriber is set as transient local, and it cannot communicate with Autoware if we publish with volatile durability. 
We should come back to discuss if this should be defined as transient local as a design, but I would like to have this merged in order to make it work with the simulator. 
I also added minor fixes:
- update timestamp in the message
- set `is_defined_acceleration` to true since we are setting acceleration field as well.
(AWSIM didn't really care with these two, though)
- https://github.com/autowarefoundation/autoware_core/issues/261
None.
None.
None.
=> fix(autoware_simple_pure_pursuit): make control command output transient local

sensing/autoware_gnss_poser/CMakeLists.txt
This fixes building the `autoware_gnss_poser` package on Ubuntu Noble. I replaced all the find package stuff with using the find module provided by Geographic lib. The call to `target_link_libraries()` wasn't needed because `ament_auto_add_library()` automatically depends on it because the rosdep key name matches the find module name: [geographiclib](https://index.ros.org/d/geographiclib/)
- Link
I'm building on Ubuntu Noble using https://github.com/ament/ament_cmake/pull/571
None.
None.
None.
=> fix(autoware_gnss_poser): depend on geographiclib through its Find module

common/autoware_trajectory/CMakeLists.txt, common/autoware_trajectory/examples/example_pose.cpp, common/autoware_trajectory/package.xml, common/autoware_trajectory/src/pose.cpp
This PR fixes two issues to get autoware_trajectory building with Rolling
* It fixes a linking issue to pybind11 libraries
* It uses non-deprecated tf2 headers because of `-Werror` causes the build to fail after https://github.com/ros2/geometry2/pull/720
- Link
Ubuntu Noble ROS Rolling with https://github.com/ament/ament_cmake/pull/571
None.
None.
None.
=> fix(autoware_trajectory): fix linking issue with pybind11, and use non-deprecated tf2 headers

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/CMakeLists.txt
autoware_motion_velocity_planner fails to find the VelocityObstacleStopModule plugin. This is due to wrong package name specified in the CMakeLists.txt. We removed the _node suffix from the motion_velocity_planner package when we ported from Universe in https://github.com/autowarefoundation/autoware_core/pull/242. 
- https://github.com/autowarefoundation/autoware_core/pull/242
I have tested with the launch file that I'm creating in this PR. https://github.com/autowarefoundation/autoware_core/pulls
None.
None.
None.
=> fix(autoware_motion_velocity_obstacle_stop_module): fix plugin export

planning/autoware_core_planning/package.xml
This PR fixes a dependency issue caused by a wrong package name:
```
▶ rosdep install -y --from-paths src --ignore-src --rosdistro $ROS_DISTRO
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
autoware_core_planning: Cannot locate rosdep definition for [autoware_behavior_velocity_planner_stop_line_module]
```
- Link
None.
None.
None.
=> fix(autoware_core_planner): fix wrong package name dependency

common/autoware_motion_utils/include/autoware/motion_utils/distance/distance.hpp, common/autoware_motion_utils/include/autoware/motion_utils/marker/marker_helper.hpp, common/autoware_motion_utils/include/autoware/motion_utils/marker/virtual_wall_marker_creator.hpp, common/autoware_motion_utils/include/autoware/motion_utils/resample/resample_utils.hpp, common/autoware_motion_utils/include/autoware/motion_utils/trajectory/trajectory.hpp, common/autoware_motion_utils/include/autoware/motion_utils/vehicle/vehicle_state_checker.hpp, common/autoware_motion_utils/test/src/trajectory/test_trajectory.cpp
This PR includes refactoring to improve memory efficiency, readability and safety without breaking the API.
- https://github.com/autowarefoundation/autoware_core/pull/343
- #345
- #346
- #347 
None.
None.
None.
=> refactor(autoware_motion_utils): rewrite using modern C++ without API breakage

common/autoware_trajectory/examples/example_readme.cpp, testing/autoware_test_utils/CMakeLists.txt
This is required for newer compilers (Jazzy) but is also more correct for Humble.
Compilation
None.
None.
None.
=> chore: include iostream and link yaml-cpp for Jazzy

planning/autoware_path_generator/src/utils.cpp
Use autoware_trajectory for cropping bounds in `crop_line_string`. These changes simplify the function without changing the behavior.
- [TIER IV Internal Slack](https://star4.slack.com/archives/C0575HP7NJG/p1742369924802139?thread_ts=1742345103.043519&cid=C0575HP7NJG)
psim
[path_generator.webm](https://github.com/user-attachments/assets/3cd389df-92ec-4d74-a1b4-8ae87b7a6536)
https://evaluation.tier4.jp/evaluation/reports/fe0540ad-4308-55e0-a13d-48919cee6add?project_id=prd_jt
None.
None.
None.
=> feat(autoware_path_generator): use autoware_trajectory for cropping bounds

planning/autoware_path_generator/include/autoware/path_generator/utils.hpp, planning/autoware_path_generator/src/utils.cpp
This PR applies refactoring to `path_generator` to avoid using fixed-size arrays and replaces them with structs.
internal: https://star4.slack.com/archives/C0575HP7NJG/p1743036870526159?thread_ts=1743033676.791979&cid=C0575HP7NJG
None.
None.
None.
=> refactor(path_generator): avoid using fixed-size array

planning/autoware_path_generator/src/utils.cpp
This PR fixes the behavior of `path_generator`'s utility functions for unintended input.
- `get_first_intersection_arc_length()` returns `std::nullopt` if either of the input lanelet sequence or the line strings generated during the process is empty
- `get_path_bounds()` returns `std::nullopt` if the input lanelet sequence is empty
- `crop_line_string()` returns the input line string as is if it consists of less than 3 points
- `crop_line_string()` returns the input line string as is if the start of the crop bound is negative or the start is larger than the end
- `get_arc_length_on_bounds()` returns 0 if the input arc length is negative
- `get_arc_length_on_centerline()` returns 0 if the input arc length is negative
2025/04/09 https://evaluation.tier4.jp/evaluation/reports/9e238d3c-7940-52 …
=> fix(path_generator): deal with unintended input

common/autoware_component_interface_specs/README.md
I found that instantiating the structs is necessary. https://github.com/autowarefoundation/autoware_core/pull/340/commits/0bb9e3a23162547d6971574f18e36e288788b2a6
- Link
None.
None.
None.
=> docs(autoware_component_interface_specs): fix `README.md`

common/autoware_component_interface_specs/README.md, common/autoware_component_interface_specs/include/autoware/component_interface_specs/utils.hpp, common/autoware_component_interface_specs/test/test_control.cpp, common/autoware_component_interface_specs/test/test_localization.cpp, common/autoware_component_interface_specs/test/test_map.cpp, common/autoware_component_interface_specs/test/test_perception.cpp, common/autoware_component_interface_specs/test/test_planning.cpp, common/autoware_component_interface_specs/test/test_vehicle.cpp, map/autoware_map_loader/src/lanelet2_map_loader/lanelet2_map_loader_node.cpp, map/autoware_map_projection_loader/src/map_projection_loader.cpp
Modify the `get_qos` function to not need an instance.
- https://github.com/autowarefoundation/autoware_core/pull/363#issuecomment-2789891663
Check if the build passes.
None.
None.
None.
=> feat(component_interface_specs): use template type in get_qos function

common/autoware_interpolation/README.md, common/autoware_motion_utils/include/autoware/motion_utils/trajectory/trajectory.hpp, common/autoware_motion_utils/test/src/trajectory/test_trajectory.cpp
Core changes for https://github.com/autowarefoundation/autoware_universe/pull/10403
Adds a yaw-constrained search for the `findFirstNearestIndexWithSoftConstraints` function that prevents mapping poses to trajectory points with large yaw deviations.
- Link
None.
None.
None.
=> fix(autoware_path_optimizer): incorrect application of input velocity due to badly mapping output trajectory to input trajectory

common/autoware_trajectory/src/point.cpp
I found a bug that accesses the element of the vector before checking the size of it. So I added the code to check it.
- https://star4.slack.com/archives/C0575HP7NJG/p1744246649555589?thread_ts=1744245439.400009&cid=C0575HP7NJG
None.
None.
None.
=> fix(autoware_trajectory): check vector size check before accessing

common/autoware_trajectory/include/autoware/trajectory/detail/interpolated_array.hpp, common/autoware_trajectory/include/autoware/trajectory/path_point.hpp, common/autoware_trajectory/include/autoware/trajectory/path_point_with_lane_id.hpp, common/autoware_trajectory/include/autoware/trajectory/trajectory_point.hpp, common/autoware_trajectory/src/path_point.cpp, common/autoware_trajectory/src/path_point_with_lane_id.cpp, common/autoware_trajectory/src/pose.cpp, common/autoware_trajectory/src/trajectory_point.cpp, common/autoware_trajectory/test/test_trajectory_container.cpp
additional fix for this PR: https://github.com/autowarefoundation/autoware_core/pull/298
`add_base_addition_callback` was properly called in each special member functions, except for move constructor which was ` = default`. This caused `add_base_addition_callback` not to be called when trajectory class was moved.
- Link
- https://evaluation.tier4.jp/evaluation/reports/dfb2238f-d498-549b-ac45-4e16c4ae841b?project_id=prd_jt
does not properly stops
https://github.com/user-attachments/assets/745f1361-12f3-4477-bc13-60dd37acc896
https://github.com/user-attachments/assets/eea2a65a-24a5-4121-9fe4-4dc11821ca72
None.
None.
None.
=> fix(autoware_trajectory): fix base_addition callback to work when Trajectory is moved

common/autoware_lanelet2_utils/include/autoware/lanelet2_utils/intersection.hpp, common/autoware_lanelet2_utils/include/autoware/lanelet2_utils/kind.hpp, common/autoware_lanelet2_utils/include/autoware/lanelet2_utils/topology.hpp, common/autoware_lanelet2_utils/src/intersection.cpp, common/autoware_lanelet2_utils/src/kind.cpp, common/autoware_lanelet2_utils/src/topology.cpp, common/autoware_lanelet2_utils/test/intersection.cpp, common/autoware_lanelet2_utils/test/kind.cpp, common/autoware_lanelet2_utils/test/topology.cpp
Since this package under development and not stable, move symbols to under `autoware::experimental`
- Link
Build/Test passes
None.
APIs move to experimental.
| Change type   | Topic Type      | Topic Name    | Message Type        | Description       |
|:--------------|:----------------|:--------------|:--------------------|:------------------|
| Added/Removed | Pub/Sub/Srv/Cli | `/topic_name` | `std_msgs/String`   | Topic description |
| Version | Topic Type      | Topic Name        | Message Type        | Description       |
|:--------|:----------------|:------------------|:--------------------|:------------------|
| Old     | Pub/Sub/Srv/Cli | `/old_topic_name` | `sensor_msgs/Image` | Topic description |
| New     | Pub/Sub/Srv/Cli | `/new_topic_name` | …
=> refactor(autoware_lanelet2_utils)!: move everything to namespace experimental

planning/autoware_path_generator/include/autoware/path_generator/node.hpp, planning/autoware_path_generator/src/node.cpp, planning/autoware_path_generator/test/test_path_generator_node_interface.cpp
Modify `path_generator` for `static_centerline_generator`.
- Moved instances from private to public.
- Moved `src/node.hpp` to `include/autoware/path_generator/node.hpp`.
* https://github.com/autowarefoundation/autoware_tools/pull/234
Psim test
None.
None.
None.
=> feat(path_generator): move generate_path public

common/autoware_object_recognition_utils/include/autoware/object_recognition_utils/matching.hpp, common/autoware_object_recognition_utils/include/autoware/object_recognition_utils/predicted_path_utils.hpp, common/autoware_object_recognition_utils/package.xml, common/autoware_object_recognition_utils/src/predicted_path_utils.cpp, common/autoware_object_recognition_utils/test/src/test_conversion.cpp, common/autoware_object_recognition_utils/test/src/test_matching.cpp, common/autoware_object_recognition_utils/test/src/test_predicted_path_utils.cpp
This PR uses `autoware_utils_*` instead of `autoware_utils`.
- https://github.com/autowarefoundation/autoware_utils/issues/53
None.
None.
None.
=> refactor(autoware_object_recognition_utils): use `autoware_utils_*` instead of `autoware_utils`

common/autoware_interpolation/include/autoware/interpolation/spline_interpolation.hpp, common/autoware_interpolation/include/autoware/interpolation/spline_interpolation_points_2d.hpp, common/autoware_interpolation/package.xml, common/autoware_interpolation/src/spline_interpolation_points_2d.cpp, common/autoware_interpolation/test/src/test_spline_interpolation.cpp, common/autoware_interpolation/test/src/test_spline_interpolation_points_2d.cpp
Use split autoware_utils packages instead of autoware_utils.
- https://github.com/autowarefoundation/autoware_utils/issues/53
Check build passes
None.
None.
None.
=> refactor(interpolation): use `autoware_utils_*` instead of `autoware_utils`

planning/autoware_route_handler/src/route_handler.cpp
Solves #356 
This PR improves route selection logic when multiple overlapping start lanelets are present by introducing a combined cost metric based on:
- Route length (meters)
- Heading difference between start pose and lanelet direction (radians)
Previously, route selection was limited by a heading difference between ego vehicle and lane orientation. This caused routes to be rejected or suboptimal even when the heading difference was negligible (e.g. <0.001 rad). This update allows more flexible and intent-aware route selection by computing a combined cost for each candidate start lanelet and choosing the one with the lowest cost.
Cost is calculated as:
`cost = path_length + angle_weight * angle_diff;`
Angle weight has been selected as 1000 to compansate the scale difference between …
=> feat(route_handler): use a cost metric to select start lane

common/autoware_trajectory/include/autoware/trajectory/detail/interpolated_array.hpp, common/autoware_trajectory/include/autoware/trajectory/path_point_with_lane_id.hpp, common/autoware_trajectory/src/path_point_with_lane_id.cpp, common/autoware_trajectory/test/test_trajectory_container.cpp
I added a member function `get_container_lane_ids`.
This function returns the unique lane ids in the trajectory in order.
- Link
Unit test.
None.
None.
None.
=> feat(autoware_trajectory): add get_contained_lane_ids function

common/autoware_trajectory/examples/example_find_intervals.cpp, common/autoware_trajectory/include/autoware/trajectory/utils/find_intervals.hpp, common/autoware_trajectory/src/utils/find_intervals.cpp, common/autoware_trajectory/test/test_trajectory_container.cpp
Previously, find_intervals function used original points of trajectory, so the accuracy of interval.start and end was poor.
For example, the following figure shows the trajectory interval which the distance from (x, y) = (0, 1) is 2, and it is calculated by previous find_intervals function.
In this PR, I introduced the binary search which enables to calculate interval.start and end exactly.
- Link
unit test and example file
None.
None.
None.
=> feat(autoware_trajectory): improve accuracy of boundary by using binary search

planning/autoware_core_planning/launch/autoware_core_planning.launch.xml
fix missing parameters error which will cause node crush when following launch step in pr https://github.com/autowarefoundation/autoware_core/pull/304
missing parameters:
1. ego_nearest_dist_threshold
2. ego_nearest_yaw_threshold
fix process
1. use existing parameters defined in config file of autoware_core_planning launch packages, file link -- https://github.com/autowarefoundation/autoware_core/blob/main/planning/autoware_core_planning/config/nearest_search.param.yaml
- Link https://github.com/autowarefoundation/autoware_core/issues/261
Following step in pr -- https://github.com/autowarefoundation/autoware_core/issues/261
Finally car start trojactory following.
None.
None.
**(EDITED by @sasakisasaki)** Bug fixes in the `autoware_path_generator` will be applied for all …
=> fix: autoware_path_generator, missing parameters in config file

planning/autoware_objects_of_interest_marker_interface/src/objects_of_interest_marker_interface.cpp
Publishing the objects of interest can become heavy when many objects are considered.
With this PR, the cost will become zero if we do not subscribe to the debug topic.
- Link
None.
None.
None.
=> perf(objects_of_interest_interface): skip publishing if no subscription

perception/autoware_ground_filter/include/autoware/ground_filter/grid.hpp, perception/autoware_ground_filter/include/autoware/ground_filter/ground_filter.hpp, perception/autoware_ground_filter/include/autoware/ground_filter/node.hpp, perception/autoware_ground_filter/package.xml, perception/autoware_ground_filter/src/node.cpp
This PR fixes the include headers of `autoware_utils` to follow the current package style (`autoware_utils_*`) for `autoware_ground_filter` package.
- https://github.com/autowarefoundation/autoware_core/issues/404
I only tested that it compiles.
None.
None.
None.
=> fix(autoware_ground_filter): fix deprecated autoware_utils header

planning/autoware_core_planning/config/motion_velocity_planner/motion_velocity_planner.param.yaml, planning/autoware_core_planning/config/motion_velocity_planner/obstacle_stop.param.yaml, planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/config/obstacle_stop.param.yaml, planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.cpp, planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/parameters.hpp, planning/motion_velocity_planner/autoware_motion_velocity_planner/config/motion_velocity_planner.param.yaml, planning/motion_velocity_planner/autoware_motion_velocity_planner/schema/motion_velocity_planner.schema.json, planning/motion_velocity_planner/autoware_motion_velocity_planner/src/node.cpp, planning/motion_velocity_planner/autoware_motion_velocity_planner/src/node.hpp, planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/planner_data.hpp, planning/motion_velocity_planner/autoware_motion_velocity_planner_common/package.xml, planning/motion_velocity_planner/autoware_motion_velocity_planner_common/src/planner_data.cpp
This PR improves point-cloud clustering by using R-Trees to filter out PointClouds that are far-away, based on a parameter, from a trajectory. Point-cloud clustering is also moved to autoware_motion_velocity_planner so that it is not done twice in autoware_obstacle_stop and autoware_obstacle_slowdown.
The timing result under update_planner_data.pcl.* shows:
1. mask-far_away_points - 3.823 ms
2. filtered_pcd_cluster - 0.356 ms
3. pcd_filter - 0.036 ms
4. process_no_ground_pointcloud - 0.495
- https://tier4.atlassian.net/browse/RT1-9554
Evaluator: https://evaluation.tier4.jp/evaluation/reports/1eb4e631-9375-5403-a5e7-0b19c4f963a6/?page=1&project_id=prd_jt (All Pass)
None.
None.
None.
=> feat(autoware_motion_velocity_planner): point-cloud clustering optimization

planning/autoware_mission_planner/package.xml, planning/autoware_mission_planner/src/lanelet2_plugins/default_planner.cpp, planning/autoware_mission_planner/src/lanelet2_plugins/default_planner.hpp, planning/autoware_mission_planner/src/lanelet2_plugins/utility_functions.cpp, planning/autoware_mission_planner/src/lanelet2_plugins/utility_functions.hpp, planning/autoware_mission_planner/src/mission_planner/arrival_checker.cpp, planning/autoware_mission_planner/src/mission_planner/mission_planner.cpp, planning/autoware_mission_planner/src/mission_planner/mission_planner.hpp, planning/autoware_mission_planner/src/mission_planner/service_utils.hpp, planning/autoware_mission_planner/test/test_lanelet2_plugins_default_planner.cpp, planning/autoware_mission_planner/test/test_utility_functions.cpp
This PR fixes the include headers of `autoware_utils` to follow the current package style (`autoware_utils_*`) for `autoware_mission_planner` package.
- https://github.com/autowarefoundation/autoware_core/issues/402
I only tested that it compiles.
None.
None.
None.
=> fix(autoware_mission_planner): fix deprecated autoware_utils header

control/autoware_simple_pure_pursuit/package.xml, control/autoware_simple_pure_pursuit/src/simple_pure_pursuit.cpp, control/autoware_simple_pure_pursuit/src/simple_pure_pursuit.hpp
This PR fixes the include headers of `autoware_utils` to follow the current package style (`autoware_utils_*`) for `autoware_simple_pure_pursuit` package.
This PR also remove the unused header.
- https://github.com/autowarefoundation/autoware_core/issues/403
I only tested that it compiles.
None.
None.
None.
=> fix(autoware_simple_pure_pursuit): fix deprecated autoware_utils header

localization/autoware_ekf_localizer/include/autoware/ekf_localizer/ekf_localizer.hpp, localization/autoware_ekf_localizer/package.xml, localization/autoware_ekf_localizer/src/covariance.cpp, localization/autoware_ekf_localizer/src/ekf_localizer.cpp, localization/autoware_ekf_localizer/src/ekf_module.cpp, localization/autoware_ekf_localizer/src/measurement.cpp
This PR fixes the include headers of `autoware_utils` to follow the current package style (`autoware_utils_*`).
It also removes unused headers.
- https://github.com/autowarefoundation/autoware_core/issues/407
- https://github.com/autowarefoundation/autoware_core/issues/410
Checked the behavior with the sample rosbag and confirmed it works as expected.
None.
None.
None.
=> fix(autoware_ekf_localizer): fix deprecated autoware_utils header

planning/autoware_path_generator/include/autoware/path_generator/utils.hpp, planning/autoware_path_generator/src/node.cpp, planning/autoware_path_generator/src/utils.cpp
In this PR, I introduced the function that smoothly connects the center line and the goal pose.
[untitled.webm](https://github.com/user-attachments/assets/5cd769e8-1fe7-44f6-9d07-32ab7a12f2cc)
This function is implemented by `autoware_trajectory`
https://tier4.atlassian.net/browse/RT1-9884
https://evaluation.tier4.jp/evaluation/reports/67a9883f-4b24-5fee-81eb-1e1c743a2c92?project_id=prd_jt
None.
None.
None.
=> feat(autoware_path_generator): add smooth goal connection

planning/autoware_route_handler/include/autoware/route_handler/route_handler.hpp, planning/autoware_route_handler/src/route_handler.cpp
to remove the `only_route_lanes` flag in other functions, this function needs to be added for goal_planner
- https://github.com/autowarefoundation/autoware_core/issues/437
https://evaluation.tier4.jp/evaluation/reports/c891c69f-30ca-5707-9d6a-7b0abce78e13?project_id=prd_jt
this functions is used in the evaluation of this PR, with no degration
https://github.com/autowarefoundation/autoware_universe/pull/10525
None.
None.
None.
=> feat(route_handler, QC): add overload of get_shoulder_lanelet_sequence

planning/autoware_path_generator/include/autoware/path_generator/utils.hpp, planning/autoware_path_generator/src/node.cpp, planning/autoware_path_generator/src/utils.cpp
This PR refactors `path_generator` to avoid using non-API functions by self implementation.
Additionally a meaningful struct instead of `std::pair` will be used.
Private: https://star4.slack.com/archives/C0575HP7NJG/p1745219385173629
Psim and `colcon test`
(ADDED by @sasakisasaki ) TIER IV internal scenario tests (success rate 114/115):
https://github.com/autowarefoundation/autoware_core/pull/432#issuecomment-2825977264
None.
None.
None.
=> refactor(path_generator): avoid using non-API functions

planning/behavior_velocity_planner/autoware_behavior_velocity_planner/include/autoware/behavior_velocity_planner/planner_manager.hpp, planning/behavior_velocity_planner/autoware_behavior_velocity_planner/src/node.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_planner/src/planner_manager.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/planner_data.hpp, planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/plugin_interface.hpp, planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/plugin_wrapper.hpp, planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/scene_module_interface.hpp, planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/utilization/util.hpp, planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/src/manager.hpp
**Needs to be merged with https://github.com/autowarefoundation/autoware_universe/pull/10546**
Currently, the behavior_velocity_planner waits for all the subscriptions (traffic_light, no_ground_pointcloud, etc) even though they are not used by the loaded plugin modules. This is contrary to the idea of the microautonomy.
Therefore, this PR makes the behavior_velocity_planner wait for only the required subscriptions which will be used by the loaded plugin modules.
- Link
planning simulator worked.
None.
The following virtual function is added to the `PluginInterface` class.
```
virtual SubscriptionData getRequiredSubscriptions() = 0;
```
None.
=> feat(behavior_velocity_planner)!: only wait for the required subscriptions

planning/autoware_route_handler/include/autoware/route_handler/route_handler.hpp, planning/autoware_route_handler/src/route_handler.cpp
This PR has actually no API influence because `only_route_lanes = false` usage is no longer found in autoware.universe
- https://github.com/autowarefoundation/autoware_universe/pull/10525
- https://github.com/autowarefoundation/autoware_core/issues/437
- https://evaluation.tier4.jp/evaluation/reports/7ce310f5-3437-5e96-89ac-75d1a595ab9a?project_id=prd_jt&state=failed
None.
None.
None.
=> feat(route_handler): remove only_route_lanes = false usage

planning/autoware_velocity_smoother/src/resample.cpp
This PR fixes `velocity_smoother` to prevent access to any element in a vector when it's empty.
Internal: https://star4.slack.com/archives/C0575HP7NJG/p1744865921175659?thread_ts=1744862416.400339&cid=C0575HP7NJG
None.
None.
None.
=> fix(velocity_smoother): prevent access when vector is empty

common/autoware_trajectory/examples/example_pose.cpp, common/autoware_trajectory/examples/example_readme.cpp, common/autoware_trajectory/src/pose.cpp
Previously, `autoware_trajectory` included `<tf2/LinearMath/Quaternion.hpp>` and `<tf2/LinearMath/Vector3.hpp>`. However, these headers might not guarantee backward compatibility. Therefore, in this PR, we replace them with `hpp` to ensure compatibility across different versions.
- Link
None.
None.
None.
=> chore(autoware_trajectory): update includes to maintain backward compatibility

planning/autoware_route_handler/src/route_handler.cpp
Resolves https://github.com/autowarefoundation/autoware_universe/issues/10295
The bug fix for the center line handling with the static_obstacle_avoidance, LC, etc.
- Before
- get the centerline
- crop the centerline
- connect the reference path and the centerline  **<-  hard to handle the full reference path and the cropped centerline**
- After
- get the centerline
- connect the reference path and the centerline
- crop the path
- Link
All the scenario tests passed. (will attach the link soon)
None.
None.
None.
=> fix(route_handler): getCenterLinePath with cropping waypoints

common/autoware_component_interface_specs/CHANGELOG.rst, common/autoware_geography_utils/CHANGELOG.rst, common/autoware_interpolation/CHANGELOG.rst, common/autoware_kalman_filter/CHANGELOG.rst, common/autoware_lanelet2_utils/CHANGELOG.rst, common/autoware_motion_utils/CHANGELOG.rst, common/autoware_object_recognition_utils/CHANGELOG.rst, common/autoware_trajectory/CHANGELOG.rst, common/autoware_vehicle_info_utils/CHANGELOG.rst, localization/autoware_localization_util/CHANGELOG.rst, map/autoware_map_loader/CHANGELOG.rst, map/autoware_map_projection_loader/CHANGELOG.rst, perception/autoware_ground_filter/CHANGELOG.rst, planning/autoware_path_generator/CHANGELOG.rst, planning/autoware_route_handler/CHANGELOG.rst, planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/CHANGELOG.rst, sensing/autoware_crop_box_filter/CHANGELOG.rst, testing/autoware_pyplot/CHANGELOG.rst, testing/autoware_test_utils/CHANGELOG.rst
Fixes URLs in the `CHANGELOG.rst`s based on the following PR
- https://github.com/autowarefoundation/autoware_core/pull/464#discussion_r2071404964
I directly accessed the fixed some URLs and could see the page.
I manually applied the fixes for `CHANGELOG.rst`s. Please let me know if this is not appropriate approach :+1: 
None.
<!-- ⬇️🔴
As this is kind of cosmetic change, I believe there'll be no effects to the system behavior.
=> docs: urls in `CHANGELOG.rst`s

planning/behavior_velocity_planner/autoware_behavior_velocity_planner/config/behavior_velocity_planner.param.yaml, planning/behavior_velocity_planner/autoware_behavior_velocity_planner/schema/behavior_velocity_planner.schema.json, planning/behavior_velocity_planner/autoware_behavior_velocity_planner/src/node.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/planner_data.hpp, planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/utilization/util.hpp, planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/utilization/util.cpp
This PR removes the unused function `behavior_velocity_planner::planning_utils::extendLine()` and its related parameter, which was replaced with `extendSegmentToBounds()` by #367.
None.
None.
None.
=> feat(behavior_velocity_planner)!: remove unused function extendLine

common/autoware_trajectory/examples/example_shift.cpp, common/autoware_trajectory/include/autoware/trajectory/point.hpp, common/autoware_trajectory/include/autoware/trajectory/utils/shift.hpp, common/autoware_trajectory/src/utils/shift.cpp, common/autoware_trajectory/test/test_shift.cpp
1. Enabled shifts to start before the beginning or after the end of the trajectory.
2. Created an interface that accepts shift_intervals as a std::vector to allow multiple consecutive shifts.
3. Removed `shift_start_s, shift_end_s` for multiple consecutive shifts
- Link
unit test
None.
None.
None.
=> feat(autoware_trajectory): enhance shift flexibility

perception/autoware_ground_filter/include/autoware/ground_filter/node.hpp
```
/opt/ros/rolling/include/message_filters/message_filters/synchronizer.h:18:2: warning: #warning This header is obsolete, please include message_filters/synchronizer.hpp instead [-Wcpp]
18 | #warning This header is obsolete, please include message_filters/synchronizer.hpp instead
|  ^~~~~~~
```
These headers are backported to humble so this works.
None.
Compiling
None.
None.
None.
=> fix: deprecation of .h files in message_filters

localization/autoware_ekf_localizer/src/warning_message.cpp
- Changed ```const``` to ```constexpr```
- Replaced ```std::string``` with ```std::string_view``` accordingly
- https://github.com/autowarefoundation/autoware_core/pull/374
- Link
- Build Passed.
None.
None.
None.
=> fix(autoware_ekf_localizer): use constexpr and string_view

planning/autoware_planning_topic_converter/package.xml, planning/autoware_planning_topic_converter/src/path_to_trajectory.cpp
This PR fixes the include headers of `autoware_utils` to follow the current package style (`autoware_utils_*`) for `autoware_planning_topic_converter` package.
- https://github.com/autowarefoundation/autoware_core/issues/402
I only tested that it compiles.
None.
None.
None.
=> fix(autoware_planning_topic_converter): fix deprecated autoware_utils header

planning/autoware_route_handler/src/route_handler.cpp
Currently, when the start point of the route planning is **on the overlapped lanes**, the route_handler selects each overlapped lane and tries to plan a route one by one.
In this case, even though the route can be planned successfully with one of the lanes, when the route_handler tries the other lane to plan a route and fails it, the following error message is given. This is not expected because the route planning is successful in the result.
In this PR
- change the level of the above message to DEBUG
- output the following error log when the route planning fails in the result
- Link
The unexpected error message is not shown on the planing simulator.
None.
None.
None.
=> fix(route_handler): fix error message for the route planning failure

planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/utilization/arc_lane_util.hpp, planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/utilization/arc_lane_util.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/test/src/test_arc_lane_util.cpp
Previously [I removed the lane_id check function from `findCollisionSegment`](https://github.com/autowarefoundation/autoware_universe/pull/7710). However, this functionality is needed when checking if the stop_line is on the specified lanelet. So I added this functionality back.
- https://github.com/autowarefoundation/autoware_universe/pull/7710
unit test
None.
None.
None.
=> fix(behavior_velocity_planner_common): support overlap lane

planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/utilization/arc_lane_util.hpp, planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/utilization/arc_lane_util.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/test/src/test_arc_lane_util.cpp
Change the argument type of lane_ids from `std::vector<size_t>` to `lanelet::Ids`.
- Link
None.
None.
None.
=> fix(behavior_velocity_planner_common): fix argument type of findCollisionSegment

.github/actions/build-and-test-differential/action.yaml, .github/workflows/build-and-test-daily.yaml, .github/workflows/build-and-test-differential-self-hosted.yaml, .github/workflows/build-and-test-differential.yaml, .github/workflows/build-and-test-self-hosted.yaml, .github/workflows/build-and-test.yaml
`autoware_core` also wants to support ROS 2 Jazzy at a community support level. Therefore, the `build-and-test*` workflows will be modified to run as a matrix for not only Humble but also Jazzy.
In this case, since Jazzy is not built using the `autoware:core-common-devel` image, its dependent packages will be installed from the ROS build farm. Also, the `build-and-test-packages-above-differential` job will only be executed with Humble.
None.
https://github.com/autowarefoundation/autoware_core/actions/runs/15063169267
None.
None.
GitHub-hosted runners usage will double.
=> feat(build-and-test*): build and test on ROS 2 Jazzy too

planning/autoware_path_generator/package.xml
A path generator package misses autoware_planning_msgs dependency
autoware_planning_msgs is used below
https://github.com/autowarefoundation/autoware_core/blob/daafec0cad104cf1ad7cabd675e4781202526355/planning/autoware_path_generator/include/autoware/path_generator/common_structs.hpp#L18
referenced in this https://github.com/autowarefoundation/autoware_core/issues/479 issue
`colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Debug --packages-up-to autoware_path_generator`
None.
None.
None.
=> fix(path_generator): add missing autoware planning msgs

common/autoware_interpolation/include/autoware/interpolation/spherical_linear_interpolation.hpp, common/autoware_motion_utils/test/src/resample/test_resample.cpp, common/autoware_motion_utils/test/src/trajectory/benchmark_calcLateralOffset.cpp, common/autoware_motion_utils/test/src/trajectory/test_interpolation.cpp, common/autoware_motion_utils/test/src/trajectory/test_trajectory.cpp, common/autoware_trajectory/examples/example_pose.cpp, common/autoware_trajectory/examples/example_readme.cpp, common/autoware_trajectory/src/pose.cpp, control/autoware_simple_pure_pursuit/src/simple_pure_pursuit.cpp, localization/autoware_ekf_localizer/include/autoware/ekf_localizer/ekf_localizer.hpp, localization/autoware_ekf_localizer/include/autoware/ekf_localizer/ekf_module.hpp, localization/autoware_ekf_localizer/src/ekf_module.cpp, localization/autoware_gyro_odometer/src/gyro_odometer_core.hpp, localization/autoware_localization_util/src/covariance_ellipse.cpp, localization/autoware_localization_util/test/test_util_func.cpp, localization/autoware_stop_filter/src/stop_filter.hpp, localization/autoware_twist2accel/src/twist2accel.hpp, perception/autoware_ground_filter/include/autoware/ground_filter/node.hpp, planning/autoware_mission_planner/src/lanelet2_plugins/default_planner.cpp, planning/autoware_mission_planner/src/mission_planner/arrival_checker.cpp, planning/autoware_mission_planner/test/test_lanelet2_plugins_default_planner.cpp, planning/autoware_route_handler/src/route_handler.cpp, planning/autoware_velocity_smoother/include/autoware/velocity_smoother/node.hpp, planning/autoware_velocity_smoother/include/autoware/velocity_smoother/smoother/analytical_jerk_constrained_smoother/analytical_jerk_constrained_smoother.hpp, planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/utilization/trajectory_utils.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/utilization/util.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/test/src/utils.hpp, planning/motion_velocity_planner/autoware_motion_velocity_planner/src/node.cpp, sensing/autoware_gnss_poser/include/autoware/gnss_poser/gnss_poser_node.hpp, testing/autoware_test_utils/src/autoware_test_utils.cpp
Fixes compilation on rolling
- Link
It compiles
None.
None.
None.
=> fix: tf2 uses hpp headers in rolling (and is backported)

.github/workflows/deploy-docs.yaml, common/autoware_interpolation/include/autoware/interpolation/spherical_linear_interpolation.hpp, common/autoware_object_recognition_utils/include/autoware/object_recognition_utils/transform.hpp, localization/autoware_localization_util/include/autoware/localization_util/util_func.hpp, localization/autoware_localization_util/src/covariance_ellipse.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_planner/src/node.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/utilization/arc_lane_util.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/utilization/trajectory_utils.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/utilization/util.cpp, sensing/autoware_gnss_poser/include/autoware/gnss_poser/gnss_poser_node.hpp
ROS 2 Galactic is no longer available from 2022.
https://docs.ros.org/en/galactic/Releases.html
This PR removes the Galactic support.
- Link
None.
None.
None.
=> chore: no longer support ROS 2 Galactic

planning/autoware_path_generator/include/autoware/path_generator/utils.hpp, planning/autoware_path_generator/src/node.cpp, planning/autoware_path_generator/src/utils.cpp
This PR fixes the path crop range calculation process when waypoints exist in the route.
Additionally, self-intersection check in the extended drivable area is fixed: https://github.com/mitukou1109/autoware_core/pull/5
Internal: https://star4.slack.com/archives/C0575HP7NJG/p1745584927722379
Psim
Before: (the path does not reach the goal)
After:
None.
None.
None.
=> fix(path_generator): fix crop range when waypoints exist

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.hpp, planning/motion_velocity_planner/autoware_motion_velocity_planner/src/node.cpp, planning/motion_velocity_planner/autoware_motion_velocity_planner/src/planner_manager.cpp, planning/motion_velocity_planner/autoware_motion_velocity_planner/src/planner_manager.hpp, planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/planner_data.hpp, planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/plugin_module_interface.hpp
**Needs to be merged with: https://github.com/autowarefoundation/autoware_universe/pull/10732**
Currently autoware_motion_velocity_planner waits for all topics (predicted_objects, no_ground_pointcloud, occupancy_grid, and traffic_light) from Perception Module although it may not need to wait for them depending on the loaded plugins.
This changes the design of motion_velocity_planner so that it will ask to each loaded plugins for required topics that needs to be subscribed and only wait for required topics. 
This is similar modification that we made to behavior_velocity_planner in [this PR](https://github.com/autowarefoundation/autoware_core/pull/433). 
- https://github.com/autowarefoundation/autoware_core/pull/433
- https://github.com/autowarefoundation/autoware_universe/pull/10732
None. …
=> feat(autoware_motion_velocity_planner)!: only wait for the required subscriptions

planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/scene_module_interface.hpp, planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/scene_module_interface.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/src/scene.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/src/scene.hpp
- print module/regulatory_element/lane/line ID and improve stop_line_module log
- `[planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner.stop_line_module]: [Module ID:9329][Lane:112][Line:9329]` 
- improve stop_line_module log
When module is triggerd
```
[component_container_mt-35] [INFO 1748500443.901859370] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner.stop_line_module]: [Module ID:9329][Lane:112][Line:9329] Module initialized (logInfo() at ../../src/autoware/core/planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/scene_module_interface.cpp:97)
```
Approaching->Stopped->Start
```
[component_container_mt-35] [INFO 1748500738.998215132] …
```
=> feat(behavior_velocity_planner_common, stop_line_module): print module/regulatory_element/lane/line ID and improve stop line module log

.github/actions/build-and-test-differential/action.yaml, .github/workflows/build-and-test-daily.yaml, .github/workflows/build-and-test.yaml
Reverts autowarefoundation/autoware_core#509
https://discourse.ros.org/t/ros-signing-key-migration-guide/43937/36
=> revert: "fix(build-and-test*.yaml): workaround of ROS signing key migration"

planning/autoware_core_planning/config/behavior_velocity_planner/behavior_velocity_planner.param.yaml, planning/autoware_planning_factor_interface/README.md, planning/autoware_planning_factor_interface/include/autoware/planning_factor_interface/planning_factor_interface.hpp, planning/behavior_velocity_planner/autoware_behavior_velocity_planner/config/behavior_velocity_planner.param.yaml, planning/behavior_velocity_planner/autoware_behavior_velocity_planner/schema/behavior_velocity_planner.schema.json, planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/planner_data.hpp, planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/scene_module_interface.hpp
Add console output option. 
This feature is helpful for debbuging of some products where we can not get rosbag
with
```
planning_factor_console_output:
enable: true
duration: 1000 # ms
```
https://github.com/user-attachments/assets/77e0f481-63bc-433d-9a7e-e6d94c52f035
- Link
psim
None.
None.
None.
=> feat(planning_factor): add console output option

planning/autoware_mission_planner/src/lanelet2_plugins/default_planner.cpp, planning/autoware_mission_planner/src/lanelet2_plugins/default_planner.hpp, planning/autoware_mission_planner/test/test_lanelet2_plugins_default_planner.cpp
port  https://github.com/autowarefoundation/autoware_universe/pull/10681
This PR fixes the procedure to check if the goal footprint is inside the route.
The fix is for the cases where the goal is on the overlapping lanes, as shown in the following video.
- Only the lanelet where the goal is located and the lanelets that are `max_longitudinal_offset_m` forward or backward from it are subject to the check.
- Create a lanelet from a line string connecting the left/right bounds of each lane.
- If left/right shoulder exists, its bound is used.
- Check that the goal footprint is fully contained within the area occupied by the combined lanelet.
https://github.com/autowarefoundation/autoware_launch/pull/1420
- Link
colcon build 
colcon test
```
1: Test command: /usr/bin/python3 …
```
=> fix(mission_planner): fix check if goal footprint is inside route

planning/autoware_route_handler/include/autoware/route_handler/route_handler.hpp, planning/autoware_route_handler/src/route_handler.cpp, planning/autoware_route_handler/test/test_route_handler.cpp
Improve performance of the `RouteHandler` when the route contains many lanelets.
- [TIER IV internal link](https://tier4.atlassian.net/browse/RT1-8421)
Psim
Evaluator (TIER IV internal link): [verification scenarios](https://evaluation.tier4.jp/evaluation/reports/fdcfaed6-99d1-5a18-b2cb-240999a2f382?project_id=prd_jt) [basic scenarios](https://evaluation.tier4.jp/evaluation/reports/56b257af-1d2d-5ed9-b5e9-4043f1472c19?project_id=prd_jt).
Example impact on the `control_evaluator` when using a route with thousands of lanelets.
| Without this PR | With this PR |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/b4d85847-a1ec-4e20-ba07-2495d5a38719) | ![image](https://github.com/user-attachments/assets/00ba6aba-9ad7-4f1f-8ffd-af191c1747d9) |
None.
None.
=> perf(route_handler): improve functions to get nearest route lanelet

localization/autoware_pose_initializer/README.md
https://github.com/autowarefoundation/autoware_core/pull/530
After porting autoware_adapi_adaptors from universe to core, the document link failed.
- Link
None.
None.
None.
=> fix(autoware_pose_initializer, autoware_adapi): fix documentation link

planning/autoware_core_planning/launch/autoware_core_planning.launch.xml, planning/autoware_mission_planner/launch/mission_planner.launch.xml, planning/autoware_mission_planner/package.xml, planning/autoware_mission_planner/src/mission_planner/mission_planner.cpp, planning/autoware_mission_planner/src/mission_planner/mission_planner.hpp
This is a follow up PR from https://github.com/autowarefoundation/autoware_core/pull/544.
This will replace the mission_planner's pub/sub/srv/cli to use the defined interface in autoware_component_interface_specs to make sure that topics and services are consistent with AD API modules.
I also changed the remap name in autoware_core_planning.launch.xml to match with the component interface topics names.
- https://github.com/autowarefoundation/autoware_core/issues/541
I have locally tested build and ran mission_planner and confirmed that it won't crash.
None.
autoware_internal_planning_msgs are replaced with autoware_planning_msgs.
This is required for compatibility with AD API.
| Version | Topic Type      | Topic Name        | Message Type        | …
=> feat: use component_interface_specs for mission_planner

planning/autoware_core_planning/config/motion_velocity_planner/obstacle_stop.param.yaml, planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/CMakeLists.txt, planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/README.md, planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/config/obstacle_stop.param.yaml, planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/package.xml, planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.cpp, planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.hpp, planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/parameters.hpp, planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/test/test_obstacle_stop_module_outside_check.cpp, planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/test/test_utils.cpp, planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/test/test_utils.hpp, planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/planner_data.hpp, planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/polygon_utils.hpp, planning/motion_velocity_planner/autoware_motion_velocity_planner_common/src/planner_data.cpp, planning/motion_velocity_planner/autoware_motion_velocity_planner_common/src/polygon_utils.cpp
This PR present new feature for the outside polygon region obstacle.
The primary objective of this feature is to initiate deceleration or a stop proactively when an object is predicted to enter the detection area due to a cut-in.
With this update, the reliability of the stop functionality for obstacles in the outside region has been improved. Therefore, this feature is now enabled by default for nearly all object types.
This feature will realize its full potential when combined with two upcoming enhancements: a stop position calculation based on RSS (Responsibility-Sensitive Safety), and the resulting expansion of the obstacle_stop module's operational speed range.
**Design Philosophy**
The obstacle_stop module is designed as a general-purpose collision avoidance feature. Our philosophy …
=> feat(obstacle_stop_module): add cut in stop feature

planning/motion_velocity_planner/autoware_motion_velocity_planner_common/README.md
It seems like there were change in pre-commit behavior and causing changes to markdown file.
This is causing irrelevant changes to some PRs making it hard to review. ([example](https://github.com/autowarefoundation/autoware_core/pull/573/commits/14fc71b08fea148f0c4f33ed49e0f324814d33cf))
- We have made the similar fix in autoware_universe: https://github.com/autowarefoundation/autoware_universe/pull/10976
None.
None.
None.
=> chore: apply pre-commit fix

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.cpp
This PR fixes a bug from PR ([link](https://github.com/autowarefoundation/autoware_core/pull/517)). The previous change, meant to stop removing objects entering the path, unintentionally caused objects exiting the path to be deflected.
https://github.com/autowarefoundation/autoware_core/pull/517
psim and tier4 scenario test
None.
None.
None.
=> fix(obstacle_stop_module): fix outside stop feature

.github/workflows/build-and-test-differential.yaml, .github/workflows/build-and-test.yaml
This PR removes the Jazzy ROS distribution from the `build-and-test` and `build-and-test-differential` workflow as it was consistently failing.
- TIER IV internal communication
- https://star4.slack.com/archives/C4P0NSMB5/p1753257668801149?thread_ts=1752751452.854389&cid=C4P0NSMB5
- [Added pull_request trigger section](https://github.com/autowarefoundation/autoware_core/pull/581/commits/40fca944fc325038a921dc077b2e59429b30141f) temporary to `.github/workflows/build-and-test.yaml` to be test-able during PR review
- CI workflows will run automatically when this PR is created/updated
- Verified that only the Humble ROS distribution job runs (Jazzy job removed)
- Both build-and-test and build-and-test-differential workflows should complete successfully without Jazzy-related failures
- …
=> fix(workflow): remove always failing job (jazzy)

planning/motion_velocity_planner/autoware_motion_velocity_planner/src/node.cpp, planning/motion_velocity_planner/autoware_motion_velocity_planner/src/node.hpp, planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/planner_data.hpp
The current implementation has the following issues due to std::make_shared() creating a copy instance and returning its shared_ptr:
- The PlannerData::Pointcloud::pcl::PointCloud<pcl::PointXYZ> instance may be copied at 10Hz.
- The scope of the copied planner_data is confusing.
This PR addresses these issues.
There are no behavioral changes by this PR.
tier4 scenario test, engage available in psim
None.
None.
None.
=> refactor(motion_velocity_planner): restrict copy of planner_data 

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/package.xml, planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/test/test_obstacle_stop_module_outside_check.cpp
Remove a wrong and unnecessary dependency on the `autoware_motion_velocity_planner` package.
- Link
None.
None.
None.
=> fix(autoware_motion_velocity_obstacle_stop_module): rm wrong dependency

planning/behavior_velocity_planner/autoware_behavior_velocity_planner/src/node.cpp
https://github.com/autowarefoundation/autoware_core/pull/610 introduced a bug that the autoware_behavior_velocity_planner's  `isDataReady=False` when using planning_simulator because the `no_ground_pointcloud` in the psim could be empty.
This PR restores the [change](https://github.com/autowarefoundation/autoware_core/pull/610/files#diff-2dfa6d4d4b1593e6dc6bd35bd8ce2ca842123421c2f69556d091166f78a4d4d6L146-L152), lets empty `no_ground_pointcloud` be acceptable.
- Link
**Private Links:**
- [Slack](https://star4.slack.com/archives/C03QW0GU6P7/p1755238241260159)
None.
None.
None.
=> fix(autoware_behavior_velocity_planner): enable empty no_ground_pointcloud

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.cpp, planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.hpp, planning/motion_velocity_planner/autoware_motion_velocity_planner_common/src/polygon_utils.cpp
This is a bug fix for the stopping algorithm during reverse driving, which was introduced when porting the obstacle_cruise_planner to the obstacle_stop_module.
before:
after:
Note that the virtual wall position in the figures denote front bumper position.
Original implementation in obstacle_cruise_planner(obsolete): https://github.com/autowarefoundation/autoware_universe/blob/0.45.0/planning/autoware_obstacle_cruise_planner/src/polygon_utils.cpp#L142-L145
None.
None.
None.
=> fix(obstacle_stop): fix bug for the backwoard motions

planning/autoware_route_handler/src/route_handler.cpp
This PR fixes the handling of cases where the specified longitudinal distance exceeds the total length of a lanelet sequence by changing `getGeometryPointFrom2DArcLength` to return `std::optional`, using `std::nullopt` when out of range, and updating call sites to safely fall back to `ref_point.point`, thereby preventing insertion of invalid `(0,0,0)` points and improving robustness of centerline path generation.
https://github.com/user-attachments/assets/db264c49-be98-4765-964e-064cdd44702a
[TIER IV INTERNAL LINK](https://star4.slack.com/archives/C03QW0GU6P7/p1756174089060889)
None.
None.
None.
=> fix(route_handler): correct handling of centerline point retrieval when requested distance is longer than lanelet length

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.cpp
fixed the following bugs
- The sign of the braking distance was not considered
- The calculation in the plan_stop function was wrong
- If the planned stop point is before the ego trajectory's first point, previously the stop point was ignored, which will be a dangerous behavior.
- With this PR, the stop point is inserted in the ego trajectory's first point.
- Link
ran the TIER IV internal scenario tests
https://evaluation.tier4.jp/evaluation/reports/048694a9-03cb-5574-9f25-be75a0f0d9a6?project_id=prd_jt
None.
None.
None.
=> fix(obstacle_stp): fix several bugs

common/autoware_marker_utils/include/autoware/marker_utils/marker_conversion.hpp, common/autoware_marker_utils/src/marker_conversion.cpp
Minor fixes from @kosuke55 [comments](https://github.com/autowarefoundation/autoware_core/pull/559#discussion_r2317638486) in PR #559.
1. change `const` to `constexpr`
2. use `calc_offset_pose` instead of hard code
3. rename input arguments to general name
- Link
None.
None.
None.
=> chore(autoware_marker_utils): convert hard code into function 

planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/utils.hpp, planning/motion_velocity_planner/autoware_motion_velocity_planner_common/src/planner_data.cpp, planning/motion_velocity_planner/autoware_motion_velocity_planner_common/src/utils.cpp
This PR decouple the cache and polygon functions.
engage available in psim
tier4 scenario test
None.
None.
=> refactor(motion_velocity_planner_common): separation of cache and polygon functions

planning/motion_velocity_planner/autoware_motion_velocity_planner/src/node.cpp
Set the correct header information when the point cloud is empty.
- tier4 scenario test
- engage available in psim
- proper header stamp is set for an empty point cloud
None.
None.
None.
=> fix(motion_velocity_planner): fix empty point cloud header

planning/motion_velocity_planner/autoware_motion_velocity_planner/src/node.cpp, planning/motion_velocity_planner/autoware_motion_velocity_planner/src/node.hpp, planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/planner_data.hpp
Publish the processed point cloud if down sampling is enabled.
- tier4 scenario test
- engage available in psim
- published point cloud can be shown in rviz
[Screencast from 2025年09月17日 13時42分07秒.webm](https://github.com/user-attachments/assets/1e7fb081-da1b-4c22-81ed-8ef20791c2ab)
None.
None.
None.
=> feat(motion_velocity_planner): update pointcloud preprocess

common/autoware_lanelet2_utils/sample_map/dense_centerline/lanelet2_map.osm
fixed the error except for `[Lane.CenterlineGeometry-001]` by running
```
ros2 run autoware_lanelet2_map_validator autoware_lanelet2_map_validator --map_file ./sample_map/dense_centerline/lanelet2_map.osm --projector mgrs
```
- Link
by using https://github.com/tier4/autoware_lanelet2_map_validator
None.
None.
None.
=> fix(autoware_lanelet2_utils): fix the map to pass validation
