.github/sync-files.yaml

Added by https://github.com/autowarefoundation/autoware.universe/pull/384.

chore: sync codecov.yaml

---

.github/CODEOWNERS-manual
.github/sync-files.yaml
.github/workflows/update-codeowners-from-packages.yaml

Same as https://github.com/autowarefoundation/autoware.universe/pull/1619.

ci: add update-codeownders-from-packages.yaml

---

.github/sync-files.yaml

Please refer to https://github.com/autowarefoundation/autoware.universe/pull/1736.

chore(sync-files): sync cancel-previous-workflows.yaml

---

.github/workflows/json-schema-check.yaml

This adds json-schema-check workflows that is used in Autoware Universe
- [Link](https://github.com/autowarefoundation/autoware.core/issues/92)
None.
None.
None.

ci: add json-schema-check workflow

---

.github/sync-files.yaml

Part of:
- https://github.com/autowarefoundation/autoware/issues/4058
- https://github.com/autowarefoundation/autoware.core/pull/79

ci(sync-files): utilize sync-file-templates repo

---

.cspell.json

This PR adds spell-check workflow which can be used for merge requirements.
Relevant: https://github.com/autowarefoundation/autoware.core/issues/92
TBD
The PR author **must** check the checkboxes below when creating the PR.
The PR reviewers **must** check the checkboxes below before approval.
The PR author **must** check the checkboxes below before merging.
After all checkboxes are checked, anyone who has write access can merge the PR.
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

ci: add spell-check local .cspell.json file

---

.github/CODEOWNERS-manual

The `autoware.core` wants to conduct strict code reviews, so this PR temporarily assigns three people as code owners for the entire codebase.
- Link
None.
None.
None.

chore: update CODEOWNERS-manual

---

.github/workflows/cppcheck-differential.yaml

This PR adjusts the suppression options to match those of `cppcheck-weekly` in order to fix the `cppcheck-differential` errors. 
https://github.com/autowarefoundation/autoware.core/actions/runs/12141461331/job/33949340069?pr=100#step:11:9
It is stricter than the one used in `autoware.universe`.
https://github.com/autowarefoundation/autoware.universe/blob/main/.cppcheck_suppressions
After merging this PR, we would like to set the `cppcheck-differential` as a required check.
- https://github.com/autowarefoundation/autoware.core/pull/100
None.
None.
None.

chore(.github): change suppression options in `cppcheck-differencial` check

---

common/autoware_geography_utils/README.md

This PR just updates the `README.md` in `autoware_geography_utils`.
None.
None.
None.

docs(autoware_geography_utils): update `README.md`

---

.github/actions/build-and-test-differential/action.yaml
.github/workflows/build-and-test-daily.yaml
.github/workflows/build-and-test-differential.yaml
.github/workflows/build-and-test.yaml

`autoware.core` is not depend on CUDA for the time being, so this PR removes the CUDA jobs.
None.
None.
None.

ci(build-and-test*): remove CUDA jobs

---

.pages
mkdocs_macros.py

This PR updates the Autoware Core Documentation page to make it closer to Autoware Universe Documentation.
This includes:
* adding mkdocs_macros to fix errors in deploy docs. https://github.com/autowarefoundation/autoware.core/actions/runs/13331935878
* adding .pages to configure top page for documentation
- https://github.com/autowarefoundation/autoware.core/issues/195
I have checked deployed page in this comment: https://github.com/autowarefoundation/autoware.core/pull/194#issuecomment-2659619437
None.
None.
None.

feat: update Documentation page for Autoware Core

---

common/autoware_trajectory/examples/example_trajectory_point.cpp
common/autoware_trajectory/include/autoware/trajectory/utils/curvature_utils.hpp
common/autoware_trajectory/test/test_trajectory_container.cpp

Add curvature_utils to calculate the maximum curvature.
Unit test.
None.
None.
None.

feat(autoware_trajectory): add curvature_utils

---

common/autoware_trajectory/include/autoware/trajectory/point.hpp
common/autoware_trajectory/include/autoware/trajectory/pose.hpp
common/autoware_trajectory/src/pose.cpp

Add a conversion function from point trajectory to pose trajectory.
- Link
None.
None.
None.

feat(autoware_trajecotry): add a conversion function from point trajectory to pose trajectory

---

.github/sync-files.yaml
.github/workflows/update-codeowners-from-packages.yaml

Continuation from:
- https://github.com/autowarefoundation/autoware.core/pull/212
Fixes the tag name.
Affected PR:
- https://github.com/autowarefoundation/autoware.core/pull/214
Simple PR, no need.
None.
None.
None.

ci(update-codeowners-from-packages): fix auto-label

---

testing/autoware_test_utils/README.md

fix invalid link
before
https://github.com/autowarefoundation/autoware.universe/tree/main/common/autoware_test_utils/test_map
after
https://github.com/autowarefoundation/autoware.core/tree/main/testing/autoware_test_utils/test_map
- Link
check link
None.
None.
None.

chore(autoware_test_utils): fix invalid link

---

.cppcheck_suppressions

Reasoning explained here:
- https://github.com/autowarefoundation/autoware.core/pull/201#issuecomment-2683921333
Similar PR:
- https://github.com/autowarefoundation/autoware.core/pull/158
Current Universe version of this file:
- https://github.com/autowarefoundation/autoware.universe/blob/769673c95d12a6361c6e3e89c5bd10ab5e1cadba/.cppcheck_suppressions#L5-L11
None.
None.
None.

chore(.cppcheck_suppressions): add checkersReport, useStlAlgorithm

---

planning/autoware_path_generator/config/path_generator.param.yaml
planning/autoware_path_generator/include/autoware/path_generator/utils.hpp
planning/autoware_path_generator/param/path_generator_parameters.yaml
planning/autoware_path_generator/src/node.cpp
planning/autoware_path_generator/src/node.hpp
planning/autoware_path_generator/src/utils.cpp

based on https://github.com/mitukou1109/autoware.core/pull/3, and fix confilcts for latest main. thnaks to @mitukou1109 
This PR adds a feature to activate turn signals based on the turn direction specified for lanelets.
https://github.com/user-attachments/assets/a15ca202-d2ef-4240-9f9b-5afb6590f424
https://github.com/user-attachments/assets/d4090212-e7cd-4db5-9124-c36a778a63c3
- https://tier4.atlassian.net/browse/RT1-9046 (internal)
- Link
- psim
-  https://evaluation.tier4.jp/evaluation/reports/03482c1b-2cb8-525c-aa33-7fdc1d22ea38?project_id=prd_jt (wip)
None.
None.
None.

feat(path_generator): add turn signal activation feature

---

common/autoware_point_types/test/test_point_types.cpp

test(autoware_point_types): add tests for missed lines

---

common/autoware_kalman_filter/test/test_kalman_filter.cpp

test(autoware_kalman_filter): add tests for missed lines

---

testing/autoware_planning_test_manager/CMakeLists.txt
testing/autoware_planning_test_manager/test/test_planning_test_manager.cpp

https://github.com/autowarefoundation/autoware.core/issues/198
Run tests locally.
None.
None.
None.

test(autoware_planning_test_manager): add tests

---

common/autoware_motion_utils/test/src/distance/test_distance.cpp
common/autoware_motion_utils/test/src/marker/test_virtual_wall_marker_creator.cpp

https://github.com/autowarefoundation/autoware.core/issues/139
Run tests successfully in local environment.
None.
None.
None.

test(autoware_motion_utils): add tests for missed lines

---

planning/autoware_path_generator/include/autoware/path_generator/utils.hpp
planning/autoware_path_generator/src/node.cpp
planning/autoware_path_generator/src/utils.cpp

This PR fixes path bound generation for overlapped lanes (based on #280).
1. When determining the end points of the path bound, the end point of the path will not be projected directly onto the bound so the bound is not cut at the outward side of the intersection. Additionally, intersection between left and right bounds will be checked and path cut will be performed if needed so the end of the return path bound will not be closer to the centerline than that of the outward one.
Before:
After:
2. Intersection between the start edge of the drivable area and path bounds will be considered to ensure the drivable area of the return path does not overlap that of the outward path.
Before:
After:
internal slack: https://star4.slack.com/archives/C0575HP7NJG/p1742256701553449
internal  ticket: …

fix(path_generator): fix path bound generation for overlapped lanes

---

common/autoware_object_recognition_utils/include/autoware/object_recognition_utils/object_classification.hpp
common/autoware_object_recognition_utils/test/src/test_object_classification.cpp

Adds missing include that causes a compiler error when building on Ubuntu Noble with ROS rolling.
```
In file included from /workspaces/ros2/src/autoware/core/autoware.core/common/autoware_object_recognition_utils/test/src/test_object_classification.cpp:15:
/workspaces/ros2/src/autoware/core/autoware.core/common/autoware_object_recognition_utils/include/autoware/object_recognition_utils/object_classification.hpp:38:13: error: ‘uint8_t’ in namespace ‘std’ does not name a type; did you mean ‘wint_t’?
38 | inline std::uint8_t getHighestProbLabel(
|             ^~~~~~~
|             wint_t
```
Including `<cstdint>` fixes it: https://en.cppreference.com/w/cpp/types/integer
- Link
ROS Rolling Ubuntu Noble with https://github.com/ament/ament_cmake/pull/571
None.
None.
None.

fix(autoware_object_recognition_utils): add missing include cstdint for std::uint8_t

---

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.cpp

Fix the topic names that were inconsistent in motion_velocity_obstacle_stop_modules.
simple planning simulator worked.
None.
None.
None.

fix(motion_velocity_obstacle_stop_module): fix debug topic name

---

common/autoware_vehicle_info_utils/include/autoware/vehicle_info_utils/vehicle_info.hpp
common/autoware_vehicle_info_utils/include/autoware/vehicle_info_utils/vehicle_info_utils.hpp
common/autoware_vehicle_info_utils/src/vehicle_info.cpp
common/autoware_vehicle_info_utils/src/vehicle_info_utils.cpp

This PR includes refactoring to improve memory efficiency, readability and safety without breaking the API.
None.
None.
None.

refactor(autoware_vehicle_info_utils): rewrite using modern C++ without API breakage

---

common/autoware_trajectory/include/autoware/trajectory/detail/helpers.hpp
common/autoware_trajectory/include/autoware/trajectory/detail/interpolated_array.hpp
common/autoware_trajectory/include/autoware/trajectory/path_point.hpp
common/autoware_trajectory/include/autoware/trajectory/path_point_with_lane_id.hpp
common/autoware_trajectory/include/autoware/trajectory/point.hpp
common/autoware_trajectory/include/autoware/trajectory/trajectory_point.hpp
common/autoware_trajectory/include/autoware/trajectory/utils/closest.hpp
common/autoware_trajectory/include/autoware/trajectory/utils/find_intervals.hpp
common/autoware_trajectory/include/autoware/trajectory/utils/shift.hpp
common/autoware_trajectory/src/path_point.cpp
common/autoware_trajectory/src/path_point_with_lane_id.cpp
common/autoware_trajectory/src/point.cpp
common/autoware_trajectory/src/pose.cpp
common/autoware_trajectory/src/trajectory_point.cpp
common/autoware_trajectory/src/utils/closest.cpp
common/autoware_trajectory/src/utils/shift.cpp

Current implementation of `get_current_base()` is very inefficient because it collects and uniquefy the base values of all fields. For example, when a new base is added to `acceleration_mps_2` of `TrajectoryPoint` container, `get_underlying_base` does the following 6 times
```cpp
// Helper function to insert elements into the set
auto insert_elements = [&unique_elements](const auto & vec) {
unique_elements.insert(vec.begin(), vec.end());
};
// Expand the parameter pack and insert elements from each vector
(insert_elements(vectors), ...); // 6 times
```
If each field has 100 bases, insertion to `set` occurs 600 times whenever `get_underlying` is called.
The insertion of a base value should much less frequent than the call to `get_underlying_base`. This PR "connects" the interpolator and …

feat(autoware_trajectory): improve performance of get_underlying_base 

---

planning/autoware_path_generator/src/node.cpp

This PR fixes `path_generator` to set both lane IDs to the point on the border of adjacent lanes.
Internal Slack link: https://star4.slack.com/archives/C0575HP7NJG/p1744691366097809?thread_ts=1744689616.743749&cid=C0575HP7NJG
Psim
Before:
After:
None.
None.
None.

fix(path_generator): set both lane IDs to point on border of adjacent lanes

---

common/autoware_qp_interface/include/autoware/qp_interface/osqp_csc_matrix_conv.hpp
common/autoware_qp_interface/include/autoware/qp_interface/osqp_interface.hpp
common/autoware_qp_interface/include/autoware/qp_interface/proxqp_interface.hpp
common/autoware_qp_interface/include/autoware/qp_interface/qp_interface.hpp
common/autoware_qp_interface/src/proxqp_interface.cpp
common/autoware_qp_interface/src/qp_interface.cpp

This PR includes refactoring to improve memory efficiency, readability and safety without breaking the API.
https://github.com/youtalk/autoware/commit/eb099aeae58f8b066a9b8417b8c39feed923ad69
https://github.com/youtalk/autoware/actions/runs/14486845705
None.
None.
None.

refactor(autoware_qp_interface): rewrite using modern C++ without API breakage

---

.github/workflows/build-and-test-differential.yaml
packages_above.repos

This adds build-and-test-packages-above-differential like we have for autoware_universe.
This modification will make sure that the modification on autoware_core won't break the build of autoware_universe.
- [relevant PR](https://github.com/autowarefoundation/autoware_universe/pull/9854)
Check this [comment](https://github.com/autowarefoundation/autoware_core/pull/408#issuecomment-2816674534). 
Instead of passing [packages-above-repos](https://github.com/autowarefoundation/autoware-github-actions/blob/6342dab2777a5466c5b549da22a9b3ec4125ea8e/colcon-build/action.yaml#L14C3-L14C23) argument to colcon-build action, I have added step to run vcs pull and remove exec depend within build-and-test-differential workflow. This is because autoware_universe has exec dependency on other repositories …

ci: add build-and-test-differential above job

---

sensing/autoware_gnss_poser/CMakeLists.txt
sensing/autoware_gnss_poser/package.xml
sensing/autoware_gnss_poser/test/test_gnss_poser_node.cpp

Add unit tests for autoware_gnss_poser.
All tests passed locally.
None.
None.
None.

test(autoware_gnss_poser): add unit tests

---

control/autoware_simple_pure_pursuit/src/simple_pure_pursuit.cpp

fix path follower lateral deviation by correcting the original control point calculation formula
before the fix, car under autoware-control always have a steady lateral deviation to the right (show in the video below)
https://github.com/user-attachments/assets/92ce9962-bc1a-436a-88b0-fce9a039a02c
after the fix, car is always in the center of the lane (show in the video below)
https://github.com/user-attachments/assets/4ffd9923-1260-49d3-b200-1843ec99e885
- Link
In order to reproduce the error, you can follow below steps:
pull AWF official docker for compile and run autoware -- ghcr.io/autowarefoundation/autoware:universe-devel-cuda
1. pull latest autoware
2. cd autoware
3. mkdir src  
4. vcs import src <  autoware.repos
5. vcs import src < autoware-nightly.repos
6. cd …

fix(autoware_simple_pure_pursuit): fix path follower lateral deviation

---

control/autoware_simple_pure_pursuit/README.md

Remove dead link from readme.
- Link
None.
None.
None.

fix(autoware_simple_pure_pursuit): fix document

---

planning/autoware_path_generator/README.md

This PR replaces the flowchart in the `path_generator`'s README with raw plantuml code.
None.
None.
None.

docs(path_generator): replace flowchart with raw plantuml code

---

control/autoware_simple_pure_pursuit/README.md
control/autoware_simple_pure_pursuit/schema/simple_pure_pursuit.schema.json

This PR adds a flowchart to `simple_pure_pursuit`'s README (which was tentatively removed by #473).
Internal Slack link: https://star4.slack.com/archives/C0575HP7NJG/p1747132023205559
None.
None.
None.

docs(simple_pure_pursuit): add flowchart

---

map/autoware_lanelet2_map_visualizer/CMakeLists.txt
map/autoware_lanelet2_map_visualizer/package.xml
map/autoware_lanelet2_map_visualizer/test/lanelet2_map_visualizer_launch.test.py
map/autoware_lanelet2_map_visualizer/test/test_lanelet2_map_visualization_node.cpp
map/autoware_lanelet2_map_visualizer/test/test_node_initialization.cpp

add unit test code
1. lanelet2_map_visualizer_launch.test.py -- make sure node can be launch and run without error
2. test_lanelet2_map_visualization_node.cpp -- check whether node can convert map to marker array
3. test_node_initialization.cpp -- make sure node can be initialized without error
- Link
1. colcon test --ctest-args tests --packages-select autoware_lanelet2_map_visualization
2. colcon test-result --all     --> show that all test passed
None.
None.
None.

test(autoware_lanelet2_map_visualization): add unit test code

---

packages_above.repos

This adds autoware_tools to packages_above.repos. 
There was a case where [the modification in Autoware Core](https://github.com/autowarefoundation/autoware_core/pull/477) [causing a failure in colcon test at autoware_tools](https://github.com/autowarefoundation/autoware_tools/pull/258).
This PR adds autoware_tools to packages_above.repos so that we can detect the affect to the autoware_tools repository before merging changes to Autoware Core. 
- https://github.com/autowarefoundation/autoware_tools/pull/258
None.
None.
None.

chore: add autoware_tools to packages_above.repos

---

common/autoware_motion_utils/include/autoware/motion_utils/trajectory/trajectory.hpp
common/autoware_motion_utils/src/trajectory/trajectory.cpp
planning/autoware_core_planning/config/motion_velocity_planner/obstacle_stop.param.yaml
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/config/obstacle_stop.param.yaml
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.hpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/parameters.hpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/path_length_buffer.hpp

Adds behaviour to the obstacle stop module so that the ego-vehicle yields to on-coming vehicles
- https://tier4.atlassian.net/browse/RT1-9226
**Design Document:**
https://tier4.atlassian.net/wiki/spaces/~712020794ae44077c44b7e9a5aa2cb085494fb/pages/3565782422/Slowing+Down+for+Opposing+Traffic
Evaluator run: https://evaluation.ci.tier4.jp/evaluation/reports/tables/new?catalog_id=095ae8b3-a23b-4a08-8674-10a681449693&filter=&job_id=a171cd53-8d11-5609-b8cd-cf8ccf340b20&project_id=prd_jt&table_config=date
Evaluator test was largely a success, however one scenario failed but not due to this change: https://evaluation.ci.tier4.jp/evaluation/reports/a171cd53-8d11-5609-b8cd-cf8ccf340b20/tests/fc18bcad-c1ca-5b60-9878-72c008d3c8d1/05a7aa12-0807-5a20-8c42-21ea98bc85d7/871fde38-5e39-5 …

feat(obstacle_stop_module): maintain larger stop distance for opposing traffic

---

planning/behavior_velocity_planner/autoware_behavior_velocity_planner/src/planner_manager.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/scene_module_interface.hpp

improve module registarion/deletion log
```
[component_container_mt-35] [INFO 1748434398.644500758] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]:
[component_container_mt-35] === BEHAVIOR VELOCITY PLANNER MODULE REGISTRATION ===
[component_container_mt-35] Module Name: stop_line
[component_container_mt-35] Module ID: 9329
[component_container_mt-35] Ego Position: (3772.31, 73732.62, 19.31)
[component_container_mt-35] Ego Velocity: (0.00, 0.00) m/s
[component_container_mt-35] Ego Stopped: Yes
[component_container_mt-35] Registered Module IDs: [9329]
[component_container_mt-35] ========================================================
[component_container_mt-35]  (printRegistrationInfo() at ../../src/autoware/core/planning/behavior_velocity_planner/auto …
```

feat(behavior_velocity_planner): improve module registraion/deletion log

---

sensing/autoware_vehicle_velocity_converter/CMakeLists.txt
sensing/autoware_vehicle_velocity_converter/test/test_vehicle_velocity_converter.cpp

Add tests for autoware_vehicle_velocity_converter.
None.
None.
None.

test(autoware_vehicle_velocity_converter): add unit tests

---

localization/autoware_pose_initializer/README.md

This PR fixes https://github.com/autowarefoundation/autoware_core/actions/runs/15488124087/job/43607355481?pr=521#step:3:472 errors.
- Link
None.
None.
None.

fix(autoware_pose_initializer): fix README.md links

---

common/autoware_trajectory/CMakeLists.txt
common/autoware_trajectory/include/autoware/trajectory/interpolator/lane_ids_interpolator.hpp
common/autoware_trajectory/src/interpolator/lane_ids_interpolator.cpp
common/autoware_trajectory/src/path_point_with_lane_id.cpp
common/autoware_trajectory/test/test_interpolator.cpp

Replace generic Stairstep interpolator with domain-specific LaneIdsInterpolator that implements lane ID interpolation logic with preference for single lane IDs.
- Add LaneIdsInterpolator implementation
- Update path_point_with_lane_id to use specialized interpolator
- Add comprehensive tests for lane ID interpolation behavior
- Includes domain knowledge for handling lane transitions
- Link
Unit test.
None.
None.
None.

feat(autoware_trajectory): add specialized LaneIdsInterpolator for lane ID handling

---

planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/scene_module_interface.hpp

Add missing `,` to `Registered Module IDs`, and print ego infomation in one line.
```
[component_container_mt-34] === BEHAVIOR VELOCITY PLANNER MODULE REGISTRATION ===
[component_container_mt-34] Module Name: intersection
[component_container_mt-34] Module ID: 190756
[component_container_mt-34] Ego Position: (89113.63, 42443.25, 6.54)
[component_container_mt-34] Ego Velocity: (0.00, 0.00) m/s
[component_container_mt-34] Ego Stopped: Yes
[component_container_mt-34] Registered Module IDs: [179280177585190756]
[component_container_mt-34] ========================================================
```
```
[component_container_mt-34] === BEHAVIOR VELOCITY PLANNER MODULE REGISTRATION ===
[component_container_mt-34] Module Name: intersection
[component_container_mt-34] Module ID: 190756 …
```

fix(behavior_velocity_planner): fix registered module ids log

---

common/autoware_component_interface_specs/CMakeLists.txt
common/autoware_component_interface_specs/include/autoware/component_interface_specs/planning.hpp
common/autoware_component_interface_specs/include/autoware/component_interface_specs/system.hpp
common/autoware_component_interface_specs/package.xml
common/autoware_component_interface_specs/test/test_system.cpp

This PR adds the following component interface definition which are used by localization and routing AD API:
- autoware_system_msgs::srv::ChangeAutowareControl
- autoware_system_msgs::srv::ChangeOperationMode
- autoware_planning_msgs::srv::SetLaneletRoute
- autoware_planning_msgs::srv::SetWaypointRoute
- autoware_planning_msgs::srv::ClearRoute
- autoware_planning_msgs::msg::RouteState
It also includes minor modification the topic name for LaneletRoute from `/planning/mission_planning/route_selector/main/route` to `/planning/route` to match with other component interface naming conventions. This topic wasn't used until now so this won't be breaking any functions in Autoware Core.
This PR must be merged before https://github.com/autowarefoundation/autoware_core/pull/543
- …

feat(autoware_component_interface_specs): update planning and system interface

---

api/autoware_core_api/CMakeLists.txt
api/autoware_core_api/README.md
api/autoware_core_api/launch/autoware_core_api.launch.xml
api/autoware_core_api/package.xml
autoware_core/launch/autoware_core.launch.xml

This adds autoware_core_api package to add launch file for api related nodes. 
- https://github.com/autowarefoundation/autoware_core/issues/541
I have built locally and ran `ros2 launch autoware_core_api autoware_core_api.launch.xml` to make sure that adapi nodes are launched correctly.
None.
None.
None.

feat: add autoware_core_api package

---

planning/autoware_path_generator/param/path_generator_parameters.yaml

The following formula should allow for a search_time of 0s, which would now be an error. Fix this problem in this PR.
https://github.com/tier4/autoware_core/blob/be8ee98bb9b3a3f410a0a5d11a815d8e0c9f9c2a/planning/autoware_path_generator/src/utils.cpp#L777
`  const auto base_search_distance = search_distance + current_vel * search_time;` 
```
[ERROR] [launch_ros.actions.load_composable_nodes]: Failed to load node 'path_generator' of type 'autoware::path_generator::PathGenerator' in container '/planning/scenario_planning/lane_driving/behavior_planning/behavior_planning_container': Component constructor threw an exception: Invalid value set during initialization for parameter 'turn_signal.search_time': Parameter 'turn_signal.search_time' with the value '0' must be greater than '0'
```
- …

fix(path_generator): support 0s turn signal search time

---

planning/autoware_path_generator/src/utils.cpp

This PR fixes the waypoint interval calculation when waypoints are on overlapped lanes.
Internal: https://star4.slack.com/archives/C0575HP7NJG/p1751601881623719
Psim
None.
None.
None.

fix(path_generator): fix waypoint interval calculation

---

common/autoware_interpolation/src/spline_interpolation_points_2d.cpp
common/autoware_motion_utils/include/autoware/motion_utils/trajectory/trajectory.hpp
common/autoware_motion_utils/src/trajectory/trajectory.cpp
common/autoware_motion_utils/test/src/trajectory/test_trajectory.cpp

- add instance of splineYawFromPoints()
- add calcElevationAngle()
NOTE: current implementation of insertOrientation() insert incorrect pitch angle.
- Link
psim and tier4 scenario tests
None.
None.
None.

fix(motion_utils): update motion utils trajectory

---

planning/autoware_path_generator/config/path_generator.param.yaml
planning/autoware_path_generator/include/autoware/path_generator/utils.hpp
planning/autoware_path_generator/param/path_generator_parameters.yaml
planning/autoware_path_generator/schema/path_generator.schema.json
planning/autoware_path_generator/src/node.cpp
planning/autoware_path_generator/src/utils.cpp

:warning: **This PR must be merged at the same time with https://github.com/autowarefoundation/autoware_launch/pull/1533** :warning: 
This PR fixes `path_generator`'s goal connection feature to accept goals far from the centerline. The new method uses the arc length from path points to the goal instead of the euclidean distance.
( the final variable name is not goal_margin but connection_section_length )
Internal: https://star4.slack.com/archives/C03QW0GU6P7/p1751438619890699?thread_ts=1746599448.646079&cid=C03QW0GU6P7
Psim
[Screencast from 2025年07月03日 17時47分36秒.webm](https://github.com/user-attachments/assets/bd03f8c8-6dc5-49f2-bfa8-c99467c9992e)
None.
None.
None.

feat(path_generator): improve goal connection for goal on the side

---

.github/actions/build-and-test-differential/action.yaml
.github/workflows/build-and-test-daily.yaml
common/autoware_geography_utils/src/height.cpp
common/autoware_geography_utils/test/test_height.cpp
map/autoware_map_projection_loader/README.md

This disables the test that depends on egm2008-1 since it is causing error in [ROS Buildfarm](https://build.ros2.org/job/Hdev__autoware_core__ubuntu_jammy_amd64/lastSuccessfulBuild/testReport/junit/autoware_geography_utils/GeographyUtils/ValidSourceTargetDatum/).
```
C++ exception with description "File not readable /usr/share/GeographicLib/geoids/egm2008-1.pgm" thrown in the test body.
```
The file is expected to be installed in [ansible](https://github.com/autowarefoundation/autoware/tree/main/ansible/roles/geographiclib), and I first tried to create a vendor package that installs this geoid file. However, due to the limitation with GitHub file size limit, it is difficult to release it as ROS vendor package. I have talked with @YamatoAndo and agreed to disable the test for now.
Since we …

fix(autoware_geography_utils): disable tests for egm2008-1

---

planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/planner_data.hpp
planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/polygon_utils.hpp
planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/utils.hpp
planning/motion_velocity_planner/autoware_motion_velocity_planner_common/src/polygon_utils.cpp

just added docstring and comments
- Link
no need to test this PR itsefl
None.
None.
None.

refactor(mvp_common): add docstrings and comments

---

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/planner_data.hpp

Just added detailed docstrings to ambiguous functions.
- Link
No need to test, as this PR only add comments
None.
None.
None.

chore(mvp_planner_common): add docstrings for PlannerData:::object

---

common/autoware_trajectory/CMakeLists.txt
localization/autoware_ndt_scan_matcher/package.xml

fix missing header file ament_index_cpp/get_package_share_directory.hpp in jazzy based compiling
compiling will raise header missing error
- Link https://github.com/autowarefoundation/autoware_core/issues/623
test with docker file produce by pr in autoware -- https://github.com/autowarefoundation/autoware/pull/6453
build command 
`colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS='-Wno-error=maybe-uninitialized -Wno-error=deprecated-declarations -Wno-error=array-bounds -Wno-error=unused-but-set-variable -Wno-error=unused-variable -Wno-dangling-reference -Wno-error=unused-function' --symlink-install --packages-up-to autoware_core`
None.
None.
None.

chore: jazzy-porting:fix missing header file

---

sensing/autoware_vehicle_velocity_converter/package.xml

Add members because the previous maintainer has left from Localization & Mapping projects.
- Link
None.
None.
None.

chore(vehicle_velocity_converter): add maintainer to vehicle_velocity_converter

---

common/autoware_lanelet2_utils/include/autoware/lanelet2_utils/conversion.hpp
common/autoware_lanelet2_utils/src/conversion.cpp

Part of this huge PR https://github.com/autowarefoundation/autoware_core/pull/625
Port following functions from autoware_lanelet2_extension
https://github.com/autowarefoundation/autoware_lanelet2_extension/blob/177078274bdde7f13116a57249dea430f2490fbf/autoware_lanelet2_extension/include/autoware_lanelet2_extension/utility/message_conversion.hpp#L39-L51
with more safe implementation
- https://github.com/autowarefoundation/autoware_core/issues/437
these functions are tested in https://github.com/autowarefoundation/autoware_core/pull/649
None.
None.
None.

feat(lanelet2_utils): port message conversion from lanelet2_extension

---

.gitignore

Ignore node_module generated by prettier.
- https://github.com/yhisaki/autoware_universe/blob/main/.gitignore
(ADDED by @sasakisasaki ) CI passed
None.
None.
None.

chore(gitignore): ignore node_module for prettier
